// Desktop Automation Protocol
// gRPC service definitions for desktop automation operations

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.1
// source: desktop.proto

package desktop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DesktopAutomation_ScreenCapture_FullMethodName = "/desktop_protocol.DesktopAutomation/ScreenCapture"
	DesktopAutomation_OcrScreen_FullMethodName     = "/desktop_protocol.DesktopAutomation/OcrScreen"
	DesktopAutomation_FindWindow_FullMethodName    = "/desktop_protocol.DesktopAutomation/FindWindow"
	DesktopAutomation_Click_FullMethodName         = "/desktop_protocol.DesktopAutomation/Click"
	DesktopAutomation_Type_FullMethodName          = "/desktop_protocol.DesktopAutomation/Type"
	DesktopAutomation_Observe_FullMethodName       = "/desktop_protocol.DesktopAutomation/Observe"
	DesktopAutomation_Decide_FullMethodName        = "/desktop_protocol.DesktopAutomation/Decide"
	DesktopAutomation_Act_FullMethodName           = "/desktop_protocol.DesktopAutomation/Act"
	DesktopAutomation_Verify_FullMethodName        = "/desktop_protocol.DesktopAutomation/Verify"
	DesktopAutomation_Recover_FullMethodName       = "/desktop_protocol.DesktopAutomation/Recover"
	DesktopAutomation_CloseSession_FullMethodName  = "/desktop_protocol.DesktopAutomation/CloseSession"
)

// DesktopAutomationClient is the client API for DesktopAutomation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Desktop automation service for Windows UI automation
type DesktopAutomationClient interface {
	// Capture screen region
	ScreenCapture(ctx context.Context, in *ScreenCaptureRequest, opts ...grpc.CallOption) (*ScreenCaptureResponse, error)
	// OCR screen region
	OcrScreen(ctx context.Context, in *OcrScreenRequest, opts ...grpc.CallOption) (*OcrScreenResponse, error)
	// Find window by title
	FindWindow(ctx context.Context, in *FindWindowRequest, opts ...grpc.CallOption) (*FindWindowResponse, error)
	// Click at coordinates
	Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ClickResponse, error)
	// Type text
	Type(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (*TypeResponse, error)
	// Observe desktop state
	Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error)
	// Make decision based on observation
	Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideResponse, error)
	// Execute action
	Act(ctx context.Context, in *ActRequest, opts ...grpc.CallOption) (*ActResponse, error)
	// Verify action result
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	// Recover from failure
	Recover(ctx context.Context, in *RecoverRequest, opts ...grpc.CallOption) (*RecoveryResponse, error)
	// Close session
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
}

type desktopAutomationClient struct {
	cc grpc.ClientConnInterface
}

func NewDesktopAutomationClient(cc grpc.ClientConnInterface) DesktopAutomationClient {
	return &desktopAutomationClient{cc}
}

func (c *desktopAutomationClient) ScreenCapture(ctx context.Context, in *ScreenCaptureRequest, opts ...grpc.CallOption) (*ScreenCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenCaptureResponse)
	err := c.cc.Invoke(ctx, DesktopAutomation_ScreenCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopAutomationClient) OcrScreen(ctx context.Context, in *OcrScreenRequest, opts ...grpc.CallOption) (*OcrScreenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OcrScreenResponse)
	err := c.cc.Invoke(ctx, DesktopAutomation_OcrScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopAutomationClient) FindWindow(ctx context.Context, in *FindWindowRequest, opts ...grpc.CallOption) (*FindWindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindWindowResponse)
	err := c.cc.Invoke(ctx, DesktopAutomation_FindWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopAutomationClient) Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ClickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClickResponse)
	err := c.cc.Invoke(ctx, DesktopAutomation_Click_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopAutomationClient) Type(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (*TypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeResponse)
	err := c.cc.Invoke(ctx, DesktopAutomation_Type_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopAutomationClient) Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObserveResponse)
	err := c.cc.Invoke(ctx, DesktopAutomation_Observe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopAutomationClient) Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecideResponse)
	err := c.cc.Invoke(ctx, DesktopAutomation_Decide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopAutomationClient) Act(ctx context.Context, in *ActRequest, opts ...grpc.CallOption) (*ActResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActResponse)
	err := c.cc.Invoke(ctx, DesktopAutomation_Act_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopAutomationClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, DesktopAutomation_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopAutomationClient) Recover(ctx context.Context, in *RecoverRequest, opts ...grpc.CallOption) (*RecoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoveryResponse)
	err := c.cc.Invoke(ctx, DesktopAutomation_Recover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *desktopAutomationClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, DesktopAutomation_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DesktopAutomationServer is the server API for DesktopAutomation service.
// All implementations must embed UnimplementedDesktopAutomationServer
// for forward compatibility.
//
// Desktop automation service for Windows UI automation
type DesktopAutomationServer interface {
	// Capture screen region
	ScreenCapture(context.Context, *ScreenCaptureRequest) (*ScreenCaptureResponse, error)
	// OCR screen region
	OcrScreen(context.Context, *OcrScreenRequest) (*OcrScreenResponse, error)
	// Find window by title
	FindWindow(context.Context, *FindWindowRequest) (*FindWindowResponse, error)
	// Click at coordinates
	Click(context.Context, *ClickRequest) (*ClickResponse, error)
	// Type text
	Type(context.Context, *TypeRequest) (*TypeResponse, error)
	// Observe desktop state
	Observe(context.Context, *ObserveRequest) (*ObserveResponse, error)
	// Make decision based on observation
	Decide(context.Context, *DecideRequest) (*DecideResponse, error)
	// Execute action
	Act(context.Context, *ActRequest) (*ActResponse, error)
	// Verify action result
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	// Recover from failure
	Recover(context.Context, *RecoverRequest) (*RecoveryResponse, error)
	// Close session
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	mustEmbedUnimplementedDesktopAutomationServer()
}

// UnimplementedDesktopAutomationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDesktopAutomationServer struct{}

func (UnimplementedDesktopAutomationServer) ScreenCapture(context.Context, *ScreenCaptureRequest) (*ScreenCaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScreenCapture not implemented")
}
func (UnimplementedDesktopAutomationServer) OcrScreen(context.Context, *OcrScreenRequest) (*OcrScreenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OcrScreen not implemented")
}
func (UnimplementedDesktopAutomationServer) FindWindow(context.Context, *FindWindowRequest) (*FindWindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindWindow not implemented")
}
func (UnimplementedDesktopAutomationServer) Click(context.Context, *ClickRequest) (*ClickResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Click not implemented")
}
func (UnimplementedDesktopAutomationServer) Type(context.Context, *TypeRequest) (*TypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Type not implemented")
}
func (UnimplementedDesktopAutomationServer) Observe(context.Context, *ObserveRequest) (*ObserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedDesktopAutomationServer) Decide(context.Context, *DecideRequest) (*DecideResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedDesktopAutomationServer) Act(context.Context, *ActRequest) (*ActResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Act not implemented")
}
func (UnimplementedDesktopAutomationServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedDesktopAutomationServer) Recover(context.Context, *RecoverRequest) (*RecoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recover not implemented")
}
func (UnimplementedDesktopAutomationServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedDesktopAutomationServer) mustEmbedUnimplementedDesktopAutomationServer() {}
func (UnimplementedDesktopAutomationServer) testEmbeddedByValue()                           {}

// UnsafeDesktopAutomationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DesktopAutomationServer will
// result in compilation errors.
type UnsafeDesktopAutomationServer interface {
	mustEmbedUnimplementedDesktopAutomationServer()
}

func RegisterDesktopAutomationServer(s grpc.ServiceRegistrar, srv DesktopAutomationServer) {
	// If the following call panics, it indicates UnimplementedDesktopAutomationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DesktopAutomation_ServiceDesc, srv)
}

func _DesktopAutomation_ScreenCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopAutomationServer).ScreenCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopAutomation_ScreenCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopAutomationServer).ScreenCapture(ctx, req.(*ScreenCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopAutomation_OcrScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OcrScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopAutomationServer).OcrScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopAutomation_OcrScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopAutomationServer).OcrScreen(ctx, req.(*OcrScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopAutomation_FindWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopAutomationServer).FindWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopAutomation_FindWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopAutomationServer).FindWindow(ctx, req.(*FindWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopAutomation_Click_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopAutomationServer).Click(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopAutomation_Click_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopAutomationServer).Click(ctx, req.(*ClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopAutomation_Type_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopAutomationServer).Type(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopAutomation_Type_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopAutomationServer).Type(ctx, req.(*TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopAutomation_Observe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopAutomationServer).Observe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopAutomation_Observe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopAutomationServer).Observe(ctx, req.(*ObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopAutomation_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopAutomationServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopAutomation_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopAutomationServer).Decide(ctx, req.(*DecideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopAutomation_Act_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopAutomationServer).Act(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopAutomation_Act_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopAutomationServer).Act(ctx, req.(*ActRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopAutomation_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopAutomationServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopAutomation_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopAutomationServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopAutomation_Recover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopAutomationServer).Recover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopAutomation_Recover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopAutomationServer).Recover(ctx, req.(*RecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DesktopAutomation_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DesktopAutomationServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DesktopAutomation_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DesktopAutomationServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DesktopAutomation_ServiceDesc is the grpc.ServiceDesc for DesktopAutomation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DesktopAutomation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "desktop_protocol.DesktopAutomation",
	HandlerType: (*DesktopAutomationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScreenCapture",
			Handler:    _DesktopAutomation_ScreenCapture_Handler,
		},
		{
			MethodName: "OcrScreen",
			Handler:    _DesktopAutomation_OcrScreen_Handler,
		},
		{
			MethodName: "FindWindow",
			Handler:    _DesktopAutomation_FindWindow_Handler,
		},
		{
			MethodName: "Click",
			Handler:    _DesktopAutomation_Click_Handler,
		},
		{
			MethodName: "Type",
			Handler:    _DesktopAutomation_Type_Handler,
		},
		{
			MethodName: "Observe",
			Handler:    _DesktopAutomation_Observe_Handler,
		},
		{
			MethodName: "Decide",
			Handler:    _DesktopAutomation_Decide_Handler,
		},
		{
			MethodName: "Act",
			Handler:    _DesktopAutomation_Act_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _DesktopAutomation_Verify_Handler,
		},
		{
			MethodName: "Recover",
			Handler:    _DesktopAutomation_Recover_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _DesktopAutomation_CloseSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desktop.proto",
}
