// Desktop Automation Protocol
// gRPC service definitions for desktop automation operations

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: desktop.proto

package desktop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Screen capture request
type ScreenCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenCaptureRequest) Reset() {
	*x = ScreenCaptureRequest{}
	mi := &file_desktop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenCaptureRequest) ProtoMessage() {}

func (x *ScreenCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenCaptureRequest.ProtoReflect.Descriptor instead.
func (*ScreenCaptureRequest) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{0}
}

func (x *ScreenCaptureRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *ScreenCaptureRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ScreenCaptureRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ScreenCaptureRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ScreenCaptureRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Screen capture response with image data
type ScreenCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // "png", "jpeg", etc.
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenCaptureResponse) Reset() {
	*x = ScreenCaptureResponse{}
	mi := &file_desktop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenCaptureResponse) ProtoMessage() {}

func (x *ScreenCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenCaptureResponse.ProtoReflect.Descriptor instead.
func (*ScreenCaptureResponse) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{1}
}

func (x *ScreenCaptureResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ScreenCaptureResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ScreenCaptureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// OCR request
type OcrScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Preprocess    bool                   `protobuf:"varint,3,opt,name=preprocess,proto3" json:"preprocess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrScreenRequest) Reset() {
	*x = OcrScreenRequest{}
	mi := &file_desktop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrScreenRequest) ProtoMessage() {}

func (x *OcrScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrScreenRequest.ProtoReflect.Descriptor instead.
func (*OcrScreenRequest) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{2}
}

func (x *OcrScreenRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *OcrScreenRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *OcrScreenRequest) GetPreprocess() bool {
	if x != nil {
		return x.Preprocess
	}
	return false
}

// OCR response with recognized text
type OcrScreenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrScreenResponse) Reset() {
	*x = OcrScreenResponse{}
	mi := &file_desktop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrScreenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrScreenResponse) ProtoMessage() {}

func (x *OcrScreenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrScreenResponse.ProtoReflect.Descriptor instead.
func (*OcrScreenResponse) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{3}
}

func (x *OcrScreenResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OcrScreenResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *OcrScreenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Find window request
type FindWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	PartialMatch  bool                   `protobuf:"varint,3,opt,name=partial_match,json=partialMatch,proto3" json:"partial_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindWindowRequest) Reset() {
	*x = FindWindowRequest{}
	mi := &file_desktop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindWindowRequest) ProtoMessage() {}

func (x *FindWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindWindowRequest.ProtoReflect.Descriptor instead.
func (*FindWindowRequest) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{4}
}

func (x *FindWindowRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindWindowRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *FindWindowRequest) GetPartialMatch() bool {
	if x != nil {
		return x.PartialMatch
	}
	return false
}

// Find window response
type FindWindowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Found         bool                   `protobuf:"varint,7,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindWindowResponse) Reset() {
	*x = FindWindowResponse{}
	mi := &file_desktop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindWindowResponse) ProtoMessage() {}

func (x *FindWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindWindowResponse.ProtoReflect.Descriptor instead.
func (*FindWindowResponse) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{5}
}

func (x *FindWindowResponse) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *FindWindowResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindWindowResponse) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FindWindowResponse) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *FindWindowResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *FindWindowResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FindWindowResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FindWindowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Click request
type ClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickRequest) Reset() {
	*x = ClickRequest{}
	mi := &file_desktop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickRequest) ProtoMessage() {}

func (x *ClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickRequest.ProtoReflect.Descriptor instead.
func (*ClickRequest) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{6}
}

func (x *ClickRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *ClickRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClickRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Click response
type ClickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickResponse) Reset() {
	*x = ClickResponse{}
	mi := &file_desktop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickResponse) ProtoMessage() {}

func (x *ClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickResponse.ProtoReflect.Descriptor instead.
func (*ClickResponse) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{7}
}

func (x *ClickResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClickResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Type request
type TypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeRequest) Reset() {
	*x = TypeRequest{}
	mi := &file_desktop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRequest) ProtoMessage() {}

func (x *TypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRequest.ProtoReflect.Descriptor instead.
func (*TypeRequest) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{8}
}

func (x *TypeRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *TypeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Type response
type TypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeResponse) Reset() {
	*x = TypeResponse{}
	mi := &file_desktop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeResponse) ProtoMessage() {}

func (x *TypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeResponse.ProtoReflect.Descriptor instead.
func (*TypeResponse) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{9}
}

func (x *TypeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TypeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Observe request
type ObserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IncludeText   bool                   `protobuf:"varint,2,opt,name=include_text,json=includeText,proto3" json:"include_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_desktop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{10}
}

func (x *ObserveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ObserveRequest) GetIncludeText() bool {
	if x != nil {
		return x.IncludeText
	}
	return false
}

// Window info message
type WindowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowInfo) Reset() {
	*x = WindowInfo{}
	mi := &file_desktop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowInfo) ProtoMessage() {}

func (x *WindowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowInfo.ProtoReflect.Descriptor instead.
func (*WindowInfo) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{11}
}

func (x *WindowInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WindowInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WindowInfo) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WindowInfo) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *WindowInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *WindowInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Observe response
type ObserveResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ObservationId       string                 `protobuf:"bytes,1,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"`
	Timestamp           string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	WindowCount         int32                  `protobuf:"varint,3,opt,name=window_count,json=windowCount,proto3" json:"window_count,omitempty"`
	Windows             []*WindowInfo          `protobuf:"bytes,4,rep,name=windows,proto3" json:"windows,omitempty"`
	TextContent         string                 `protobuf:"bytes,5,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	ScreenshotAvailable bool                   `protobuf:"varint,6,opt,name=screenshot_available,json=screenshotAvailable,proto3" json:"screenshot_available,omitempty"`
	Error               string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ObserveResponse) Reset() {
	*x = ObserveResponse{}
	mi := &file_desktop_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveResponse) ProtoMessage() {}

func (x *ObserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveResponse.ProtoReflect.Descriptor instead.
func (*ObserveResponse) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{12}
}

func (x *ObserveResponse) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

func (x *ObserveResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ObserveResponse) GetWindowCount() int32 {
	if x != nil {
		return x.WindowCount
	}
	return 0
}

func (x *ObserveResponse) GetWindows() []*WindowInfo {
	if x != nil {
		return x.Windows
	}
	return nil
}

func (x *ObserveResponse) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *ObserveResponse) GetScreenshotAvailable() bool {
	if x != nil {
		return x.ScreenshotAvailable
	}
	return false
}

func (x *ObserveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Decision request
type DecideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObservationId string                 `protobuf:"bytes,1,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_desktop_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{13}
}

func (x *DecideRequest) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

// Decision response action
type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // "click", "type", "screenshot"
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ActionId      string                 `protobuf:"bytes,7,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_desktop_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{14}
}

func (x *Action) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *Action) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Action) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Action) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Action) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Action) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Action) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

// Decision response
type DecideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObservationId string                 `protobuf:"bytes,1,opt,name=observation_id,json=observationId,proto3" json:"observation_id,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideResponse) Reset() {
	*x = DecideResponse{}
	mi := &file_desktop_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideResponse) ProtoMessage() {}

func (x *DecideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideResponse.ProtoReflect.Descriptor instead.
func (*DecideResponse) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{15}
}

func (x *DecideResponse) GetObservationId() string {
	if x != nil {
		return x.ObservationId
	}
	return ""
}

func (x *DecideResponse) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *DecideResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Act request
type ActRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActRequest) Reset() {
	*x = ActRequest{}
	mi := &file_desktop_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActRequest) ProtoMessage() {}

func (x *ActRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActRequest.ProtoReflect.Descriptor instead.
func (*ActRequest) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{16}
}

func (x *ActRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ActRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

// Act response
type ActResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ActionId      string                 `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Screenshot    []byte                 `protobuf:"bytes,3,opt,name=screenshot,proto3" json:"screenshot,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActResponse) Reset() {
	*x = ActResponse{}
	mi := &file_desktop_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActResponse) ProtoMessage() {}

func (x *ActResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActResponse.ProtoReflect.Descriptor instead.
func (*ActResponse) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{17}
}

func (x *ActResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActResponse) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ActResponse) GetScreenshot() []byte {
	if x != nil {
		return x.Screenshot
	}
	return nil
}

func (x *ActResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Verify request
type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	ExpectedState string                 `protobuf:"bytes,3,opt,name=expected_state,json=expectedState,proto3" json:"expected_state,omitempty"`
	ActualState   string                 `protobuf:"bytes,4,opt,name=actual_state,json=actualState,proto3" json:"actual_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_desktop_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{18}
}

func (x *VerifyRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VerifyRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *VerifyRequest) GetExpectedState() string {
	if x != nil {
		return x.ExpectedState
	}
	return ""
}

func (x *VerifyRequest) GetActualState() string {
	if x != nil {
		return x.ActualState
	}
	return ""
}

// Verify response
type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_desktop_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{19}
}

func (x *VerifyResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *VerifyResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *VerifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Recover request
type RecoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FailureType   string                 `protobuf:"bytes,2,opt,name=failure_type,json=failureType,proto3" json:"failure_type,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverRequest) Reset() {
	*x = RecoverRequest{}
	mi := &file_desktop_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverRequest) ProtoMessage() {}

func (x *RecoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverRequest.ProtoReflect.Descriptor instead.
func (*RecoverRequest) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{20}
}

func (x *RecoverRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecoverRequest) GetFailureType() string {
	if x != nil {
		return x.FailureType
	}
	return ""
}

func (x *RecoverRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

// Recovery response
type RecoveryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecoveryAction string                 `protobuf:"bytes,2,opt,name=recovery_action,json=recoveryAction,proto3" json:"recovery_action,omitempty"`
	Notes          string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecoveryResponse) Reset() {
	*x = RecoveryResponse{}
	mi := &file_desktop_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryResponse) ProtoMessage() {}

func (x *RecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryResponse.ProtoReflect.Descriptor instead.
func (*RecoveryResponse) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{21}
}

func (x *RecoveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecoveryResponse) GetRecoveryAction() string {
	if x != nil {
		return x.RecoveryAction
	}
	return ""
}

func (x *RecoveryResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *RecoveryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Close session request
type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_desktop_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{22}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Close session response
type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_desktop_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_desktop_proto_rawDescGZIP(), []int{23}
}

func (x *CloseSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_desktop_proto protoreflect.FileDescriptor

const file_desktop_proto_rawDesc = "" +
	"\n" +
	"\rdesktop.proto\x12\x10desktop_protocol\"}\n" +
	"\x14ScreenCaptureRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\"d\n" +
	"\x15ScreenCaptureResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"m\n" +
	"\x10OcrScreenRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"preprocess\x18\x03 \x01(\bR\n" +
	"preprocess\"]\n" +
	"\x11OcrScreenResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"m\n" +
	"\x11FindWindowRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\x12#\n" +
	"\rpartial_match\x18\x03 \x01(\bR\fpartialMatch\"\xbd\x01\n" +
	"\x12FindWindowResponse\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12\x14\n" +
	"\x05found\x18\a \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"G\n" +
	"\fClickRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"?\n" +
	"\rClickResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\vTypeRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\">\n" +
	"\fTypeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"R\n" +
	"\x0eObserveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\finclude_text\x18\x02 \x01(\bR\vincludeText\"|\n" +
	"\n" +
	"WindowInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\"\x9d\x02\n" +
	"\x0fObserveResponse\x12%\n" +
	"\x0eobservation_id\x18\x01 \x01(\tR\robservationId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12!\n" +
	"\fwindow_count\x18\x03 \x01(\x05R\vwindowCount\x126\n" +
	"\awindows\x18\x04 \x03(\v2\x1c.desktop_protocol.WindowInfoR\awindows\x12!\n" +
	"\ftext_content\x18\x05 \x01(\tR\vtextContent\x121\n" +
	"\x14screenshot_available\x18\x06 \x01(\bR\x13screenshotAvailable\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"6\n" +
	"\rDecideRequest\x12%\n" +
	"\x0eobservation_id\x18\x01 \x01(\tR\robservationId\"\xae\x01\n" +
	"\x06Action\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\x12\x1b\n" +
	"\taction_id\x18\a \x01(\tR\bactionId\"\x7f\n" +
	"\x0eDecideResponse\x12%\n" +
	"\x0eobservation_id\x18\x01 \x01(\tR\robservationId\x120\n" +
	"\x06action\x18\x02 \x01(\v2\x18.desktop_protocol.ActionR\x06action\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"]\n" +
	"\n" +
	"ActRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\x06action\x18\x02 \x01(\v2\x18.desktop_protocol.ActionR\x06action\"z\n" +
	"\vActResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\tR\bactionId\x12\x1e\n" +
	"\n" +
	"screenshot\x18\x03 \x01(\fR\n" +
	"screenshot\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xaa\x01\n" +
	"\rVerifyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\x06action\x18\x02 \x01(\v2\x18.desktop_protocol.ActionR\x06action\x12%\n" +
	"\x0eexpected_state\x18\x03 \x01(\tR\rexpectedState\x12!\n" +
	"\factual_state\x18\x04 \x01(\tR\vactualState\"x\n" +
	"\x0eVerifyResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"l\n" +
	"\x0eRecoverRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\ffailure_type\x18\x02 \x01(\tR\vfailureType\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\"\x81\x01\n" +
	"\x10RecoveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0frecovery_action\x18\x02 \x01(\tR\x0erecoveryAction\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"F\n" +
	"\x14CloseSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x93\a\n" +
	"\x11DesktopAutomation\x12`\n" +
	"\rScreenCapture\x12&.desktop_protocol.ScreenCaptureRequest\x1a'.desktop_protocol.ScreenCaptureResponse\x12T\n" +
	"\tOcrScreen\x12\".desktop_protocol.OcrScreenRequest\x1a#.desktop_protocol.OcrScreenResponse\x12W\n" +
	"\n" +
	"FindWindow\x12#.desktop_protocol.FindWindowRequest\x1a$.desktop_protocol.FindWindowResponse\x12H\n" +
	"\x05Click\x12\x1e.desktop_protocol.ClickRequest\x1a\x1f.desktop_protocol.ClickResponse\x12E\n" +
	"\x04Type\x12\x1d.desktop_protocol.TypeRequest\x1a\x1e.desktop_protocol.TypeResponse\x12N\n" +
	"\aObserve\x12 .desktop_protocol.ObserveRequest\x1a!.desktop_protocol.ObserveResponse\x12K\n" +
	"\x06Decide\x12\x1f.desktop_protocol.DecideRequest\x1a .desktop_protocol.DecideResponse\x12B\n" +
	"\x03Act\x12\x1c.desktop_protocol.ActRequest\x1a\x1d.desktop_protocol.ActResponse\x12K\n" +
	"\x06Verify\x12\x1f.desktop_protocol.VerifyRequest\x1a .desktop_protocol.VerifyResponse\x12O\n" +
	"\aRecover\x12 .desktop_protocol.RecoverRequest\x1a\".desktop_protocol.RecoveryResponse\x12]\n" +
	"\fCloseSession\x12%.desktop_protocol.CloseSessionRequest\x1a&.desktop_protocol.CloseSessionResponseB;Z9github.com/AgentOS/agentos-runtime/internal/proto/desktopb\x06proto3"

var (
	file_desktop_proto_rawDescOnce sync.Once
	file_desktop_proto_rawDescData []byte
)

func file_desktop_proto_rawDescGZIP() []byte {
	file_desktop_proto_rawDescOnce.Do(func() {
		file_desktop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_desktop_proto_rawDesc), len(file_desktop_proto_rawDesc)))
	})
	return file_desktop_proto_rawDescData
}

var file_desktop_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_desktop_proto_goTypes = []any{
	(*ScreenCaptureRequest)(nil),  // 0: desktop_protocol.ScreenCaptureRequest
	(*ScreenCaptureResponse)(nil), // 1: desktop_protocol.ScreenCaptureResponse
	(*OcrScreenRequest)(nil),      // 2: desktop_protocol.OcrScreenRequest
	(*OcrScreenResponse)(nil),     // 3: desktop_protocol.OcrScreenResponse
	(*FindWindowRequest)(nil),     // 4: desktop_protocol.FindWindowRequest
	(*FindWindowResponse)(nil),    // 5: desktop_protocol.FindWindowResponse
	(*ClickRequest)(nil),          // 6: desktop_protocol.ClickRequest
	(*ClickResponse)(nil),         // 7: desktop_protocol.ClickResponse
	(*TypeRequest)(nil),           // 8: desktop_protocol.TypeRequest
	(*TypeResponse)(nil),          // 9: desktop_protocol.TypeResponse
	(*ObserveRequest)(nil),        // 10: desktop_protocol.ObserveRequest
	(*WindowInfo)(nil),            // 11: desktop_protocol.WindowInfo
	(*ObserveResponse)(nil),       // 12: desktop_protocol.ObserveResponse
	(*DecideRequest)(nil),         // 13: desktop_protocol.DecideRequest
	(*Action)(nil),                // 14: desktop_protocol.Action
	(*DecideResponse)(nil),        // 15: desktop_protocol.DecideResponse
	(*ActRequest)(nil),            // 16: desktop_protocol.ActRequest
	(*ActResponse)(nil),           // 17: desktop_protocol.ActResponse
	(*VerifyRequest)(nil),         // 18: desktop_protocol.VerifyRequest
	(*VerifyResponse)(nil),        // 19: desktop_protocol.VerifyResponse
	(*RecoverRequest)(nil),        // 20: desktop_protocol.RecoverRequest
	(*RecoveryResponse)(nil),      // 21: desktop_protocol.RecoveryResponse
	(*CloseSessionRequest)(nil),   // 22: desktop_protocol.CloseSessionRequest
	(*CloseSessionResponse)(nil),  // 23: desktop_protocol.CloseSessionResponse
}
var file_desktop_proto_depIdxs = []int32{
	11, // 0: desktop_protocol.ObserveResponse.windows:type_name -> desktop_protocol.WindowInfo
	14, // 1: desktop_protocol.DecideResponse.action:type_name -> desktop_protocol.Action
	14, // 2: desktop_protocol.ActRequest.action:type_name -> desktop_protocol.Action
	14, // 3: desktop_protocol.VerifyRequest.action:type_name -> desktop_protocol.Action
	0,  // 4: desktop_protocol.DesktopAutomation.ScreenCapture:input_type -> desktop_protocol.ScreenCaptureRequest
	2,  // 5: desktop_protocol.DesktopAutomation.OcrScreen:input_type -> desktop_protocol.OcrScreenRequest
	4,  // 6: desktop_protocol.DesktopAutomation.FindWindow:input_type -> desktop_protocol.FindWindowRequest
	6,  // 7: desktop_protocol.DesktopAutomation.Click:input_type -> desktop_protocol.ClickRequest
	8,  // 8: desktop_protocol.DesktopAutomation.Type:input_type -> desktop_protocol.TypeRequest
	10, // 9: desktop_protocol.DesktopAutomation.Observe:input_type -> desktop_protocol.ObserveRequest
	13, // 10: desktop_protocol.DesktopAutomation.Decide:input_type -> desktop_protocol.DecideRequest
	16, // 11: desktop_protocol.DesktopAutomation.Act:input_type -> desktop_protocol.ActRequest
	18, // 12: desktop_protocol.DesktopAutomation.Verify:input_type -> desktop_protocol.VerifyRequest
	20, // 13: desktop_protocol.DesktopAutomation.Recover:input_type -> desktop_protocol.RecoverRequest
	22, // 14: desktop_protocol.DesktopAutomation.CloseSession:input_type -> desktop_protocol.CloseSessionRequest
	1,  // 15: desktop_protocol.DesktopAutomation.ScreenCapture:output_type -> desktop_protocol.ScreenCaptureResponse
	3,  // 16: desktop_protocol.DesktopAutomation.OcrScreen:output_type -> desktop_protocol.OcrScreenResponse
	5,  // 17: desktop_protocol.DesktopAutomation.FindWindow:output_type -> desktop_protocol.FindWindowResponse
	7,  // 18: desktop_protocol.DesktopAutomation.Click:output_type -> desktop_protocol.ClickResponse
	9,  // 19: desktop_protocol.DesktopAutomation.Type:output_type -> desktop_protocol.TypeResponse
	12, // 20: desktop_protocol.DesktopAutomation.Observe:output_type -> desktop_protocol.ObserveResponse
	15, // 21: desktop_protocol.DesktopAutomation.Decide:output_type -> desktop_protocol.DecideResponse
	17, // 22: desktop_protocol.DesktopAutomation.Act:output_type -> desktop_protocol.ActResponse
	19, // 23: desktop_protocol.DesktopAutomation.Verify:output_type -> desktop_protocol.VerifyResponse
	21, // 24: desktop_protocol.DesktopAutomation.Recover:output_type -> desktop_protocol.RecoveryResponse
	23, // 25: desktop_protocol.DesktopAutomation.CloseSession:output_type -> desktop_protocol.CloseSessionResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_desktop_proto_init() }
func file_desktop_proto_init() {
	if File_desktop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_desktop_proto_rawDesc), len(file_desktop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_desktop_proto_goTypes,
		DependencyIndexes: file_desktop_proto_depIdxs,
		MessageInfos:      file_desktop_proto_msgTypes,
	}.Build()
	File_desktop_proto = out.File
	file_desktop_proto_goTypes = nil
	file_desktop_proto_depIdxs = nil
}
