// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.1
// source: worker.proto

package worker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerExecutor_ExecuteTask_FullMethodName = "/worker.WorkerExecutor/ExecuteTask"
	WorkerExecutor_HealthCheck_FullMethodName = "/worker.WorkerExecutor/HealthCheck"
)

// WorkerExecutorClient is the client API for WorkerExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Task execution service for Go worker pool to Python executor communication
type WorkerExecutorClient interface {
	// Execute a task
	ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type workerExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerExecutorClient(cc grpc.ClientConnInterface) WorkerExecutorClient {
	return &workerExecutorClient{cc}
}

func (c *workerExecutorClient) ExecuteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, WorkerExecutor_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerExecutorClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, WorkerExecutor_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerExecutorServer is the server API for WorkerExecutor service.
// All implementations must embed UnimplementedWorkerExecutorServer
// for forward compatibility.
//
// Task execution service for Go worker pool to Python executor communication
type WorkerExecutorServer interface {
	// Execute a task
	ExecuteTask(context.Context, *TaskRequest) (*TaskResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedWorkerExecutorServer()
}

// UnimplementedWorkerExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerExecutorServer struct{}

func (UnimplementedWorkerExecutorServer) ExecuteTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedWorkerExecutorServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWorkerExecutorServer) mustEmbedUnimplementedWorkerExecutorServer() {}
func (UnimplementedWorkerExecutorServer) testEmbeddedByValue()                        {}

// UnsafeWorkerExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerExecutorServer will
// result in compilation errors.
type UnsafeWorkerExecutorServer interface {
	mustEmbedUnimplementedWorkerExecutorServer()
}

func RegisterWorkerExecutorServer(s grpc.ServiceRegistrar, srv WorkerExecutorServer) {
	// If the following call panics, it indicates UnimplementedWorkerExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerExecutor_ServiceDesc, srv)
}

func _WorkerExecutor_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerExecutorServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerExecutor_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerExecutorServer).ExecuteTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerExecutor_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerExecutorServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerExecutor_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerExecutorServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerExecutor_ServiceDesc is the grpc.ServiceDesc for WorkerExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.WorkerExecutor",
	HandlerType: (*WorkerExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTask",
			Handler:    _WorkerExecutor_ExecuteTask_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _WorkerExecutor_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker.proto",
}
