# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import desktop_pb2 as desktop__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in desktop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DesktopAutomationStub(object):
    """Desktop automation service for Windows UI automation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScreenCapture = channel.unary_unary(
                '/desktop_protocol.DesktopAutomation/ScreenCapture',
                request_serializer=desktop__pb2.ScreenCaptureRequest.SerializeToString,
                response_deserializer=desktop__pb2.ScreenCaptureResponse.FromString,
                _registered_method=True)
        self.OcrScreen = channel.unary_unary(
                '/desktop_protocol.DesktopAutomation/OcrScreen',
                request_serializer=desktop__pb2.OcrScreenRequest.SerializeToString,
                response_deserializer=desktop__pb2.OcrScreenResponse.FromString,
                _registered_method=True)
        self.FindWindow = channel.unary_unary(
                '/desktop_protocol.DesktopAutomation/FindWindow',
                request_serializer=desktop__pb2.FindWindowRequest.SerializeToString,
                response_deserializer=desktop__pb2.FindWindowResponse.FromString,
                _registered_method=True)
        self.Click = channel.unary_unary(
                '/desktop_protocol.DesktopAutomation/Click',
                request_serializer=desktop__pb2.ClickRequest.SerializeToString,
                response_deserializer=desktop__pb2.ClickResponse.FromString,
                _registered_method=True)
        self.Type = channel.unary_unary(
                '/desktop_protocol.DesktopAutomation/Type',
                request_serializer=desktop__pb2.TypeRequest.SerializeToString,
                response_deserializer=desktop__pb2.TypeResponse.FromString,
                _registered_method=True)
        self.Observe = channel.unary_unary(
                '/desktop_protocol.DesktopAutomation/Observe',
                request_serializer=desktop__pb2.ObserveRequest.SerializeToString,
                response_deserializer=desktop__pb2.ObserveResponse.FromString,
                _registered_method=True)
        self.Decide = channel.unary_unary(
                '/desktop_protocol.DesktopAutomation/Decide',
                request_serializer=desktop__pb2.DecideRequest.SerializeToString,
                response_deserializer=desktop__pb2.DecideResponse.FromString,
                _registered_method=True)
        self.Act = channel.unary_unary(
                '/desktop_protocol.DesktopAutomation/Act',
                request_serializer=desktop__pb2.ActRequest.SerializeToString,
                response_deserializer=desktop__pb2.ActResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/desktop_protocol.DesktopAutomation/Verify',
                request_serializer=desktop__pb2.VerifyRequest.SerializeToString,
                response_deserializer=desktop__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.Recover = channel.unary_unary(
                '/desktop_protocol.DesktopAutomation/Recover',
                request_serializer=desktop__pb2.RecoverRequest.SerializeToString,
                response_deserializer=desktop__pb2.RecoveryResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/desktop_protocol.DesktopAutomation/CloseSession',
                request_serializer=desktop__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=desktop__pb2.CloseSessionResponse.FromString,
                _registered_method=True)


class DesktopAutomationServicer(object):
    """Desktop automation service for Windows UI automation
    """

    def ScreenCapture(self, request, context):
        """Capture screen region
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OcrScreen(self, request, context):
        """OCR screen region
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindWindow(self, request, context):
        """Find window by title
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Click(self, request, context):
        """Click at coordinates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Type(self, request, context):
        """Type text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Observe desktop state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decide(self, request, context):
        """Make decision based on observation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Act(self, request, context):
        """Execute action
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Verify action result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recover(self, request, context):
        """Recover from failure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Close session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DesktopAutomationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScreenCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.ScreenCapture,
                    request_deserializer=desktop__pb2.ScreenCaptureRequest.FromString,
                    response_serializer=desktop__pb2.ScreenCaptureResponse.SerializeToString,
            ),
            'OcrScreen': grpc.unary_unary_rpc_method_handler(
                    servicer.OcrScreen,
                    request_deserializer=desktop__pb2.OcrScreenRequest.FromString,
                    response_serializer=desktop__pb2.OcrScreenResponse.SerializeToString,
            ),
            'FindWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.FindWindow,
                    request_deserializer=desktop__pb2.FindWindowRequest.FromString,
                    response_serializer=desktop__pb2.FindWindowResponse.SerializeToString,
            ),
            'Click': grpc.unary_unary_rpc_method_handler(
                    servicer.Click,
                    request_deserializer=desktop__pb2.ClickRequest.FromString,
                    response_serializer=desktop__pb2.ClickResponse.SerializeToString,
            ),
            'Type': grpc.unary_unary_rpc_method_handler(
                    servicer.Type,
                    request_deserializer=desktop__pb2.TypeRequest.FromString,
                    response_serializer=desktop__pb2.TypeResponse.SerializeToString,
            ),
            'Observe': grpc.unary_unary_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=desktop__pb2.ObserveRequest.FromString,
                    response_serializer=desktop__pb2.ObserveResponse.SerializeToString,
            ),
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=desktop__pb2.DecideRequest.FromString,
                    response_serializer=desktop__pb2.DecideResponse.SerializeToString,
            ),
            'Act': grpc.unary_unary_rpc_method_handler(
                    servicer.Act,
                    request_deserializer=desktop__pb2.ActRequest.FromString,
                    response_serializer=desktop__pb2.ActResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=desktop__pb2.VerifyRequest.FromString,
                    response_serializer=desktop__pb2.VerifyResponse.SerializeToString,
            ),
            'Recover': grpc.unary_unary_rpc_method_handler(
                    servicer.Recover,
                    request_deserializer=desktop__pb2.RecoverRequest.FromString,
                    response_serializer=desktop__pb2.RecoveryResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=desktop__pb2.CloseSessionRequest.FromString,
                    response_serializer=desktop__pb2.CloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'desktop_protocol.DesktopAutomation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('desktop_protocol.DesktopAutomation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DesktopAutomation(object):
    """Desktop automation service for Windows UI automation
    """

    @staticmethod
    def ScreenCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktop_protocol.DesktopAutomation/ScreenCapture',
            desktop__pb2.ScreenCaptureRequest.SerializeToString,
            desktop__pb2.ScreenCaptureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OcrScreen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktop_protocol.DesktopAutomation/OcrScreen',
            desktop__pb2.OcrScreenRequest.SerializeToString,
            desktop__pb2.OcrScreenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktop_protocol.DesktopAutomation/FindWindow',
            desktop__pb2.FindWindowRequest.SerializeToString,
            desktop__pb2.FindWindowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Click(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktop_protocol.DesktopAutomation/Click',
            desktop__pb2.ClickRequest.SerializeToString,
            desktop__pb2.ClickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Type(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktop_protocol.DesktopAutomation/Type',
            desktop__pb2.TypeRequest.SerializeToString,
            desktop__pb2.TypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktop_protocol.DesktopAutomation/Observe',
            desktop__pb2.ObserveRequest.SerializeToString,
            desktop__pb2.ObserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktop_protocol.DesktopAutomation/Decide',
            desktop__pb2.DecideRequest.SerializeToString,
            desktop__pb2.DecideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Act(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktop_protocol.DesktopAutomation/Act',
            desktop__pb2.ActRequest.SerializeToString,
            desktop__pb2.ActResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktop_protocol.DesktopAutomation/Verify',
            desktop__pb2.VerifyRequest.SerializeToString,
            desktop__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktop_protocol.DesktopAutomation/Recover',
            desktop__pb2.RecoverRequest.SerializeToString,
            desktop__pb2.RecoveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktop_protocol.DesktopAutomation/CloseSession',
            desktop__pb2.CloseSessionRequest.SerializeToString,
            desktop__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
