// This file is @generated by prost-build.
/// Screen capture request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScreenCaptureRequest {
    #[prost(string, tag = "1")]
    pub window_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub x: i32,
    #[prost(int32, tag = "3")]
    pub y: i32,
    #[prost(int32, tag = "4")]
    pub width: i32,
    #[prost(int32, tag = "5")]
    pub height: i32,
}
/// Screen capture response with image data
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScreenCaptureResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub image_data: ::prost::alloc::vec::Vec<u8>,
    /// "png", "jpeg", etc.
    #[prost(string, tag = "2")]
    pub format: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
/// OCR request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OcrScreenRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub image_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub language: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub preprocess: bool,
}
/// OCR response with recognized text
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OcrScreenResponse {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub confidence: f32,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
/// Find window request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindWindowRequest {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub partial_match: bool,
}
/// Find window response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FindWindowResponse {
    #[prost(string, tag = "1")]
    pub window_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub x: i32,
    #[prost(int32, tag = "4")]
    pub y: i32,
    #[prost(int32, tag = "5")]
    pub width: i32,
    #[prost(int32, tag = "6")]
    pub height: i32,
    #[prost(bool, tag = "7")]
    pub found: bool,
    #[prost(string, tag = "8")]
    pub error: ::prost::alloc::string::String,
}
/// Click request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClickRequest {
    #[prost(string, tag = "1")]
    pub window_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub x: i32,
    #[prost(int32, tag = "3")]
    pub y: i32,
}
/// Click response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClickResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Type request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypeRequest {
    #[prost(string, tag = "1")]
    pub window_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub text: ::prost::alloc::string::String,
}
/// Type response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypeResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Observe request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObserveRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub include_text: bool,
}
/// Window info message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WindowInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub x: i32,
    #[prost(int32, tag = "4")]
    pub y: i32,
    #[prost(int32, tag = "5")]
    pub width: i32,
    #[prost(int32, tag = "6")]
    pub height: i32,
}
/// Observe response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObserveResponse {
    #[prost(string, tag = "1")]
    pub observation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub window_count: i32,
    #[prost(message, repeated, tag = "4")]
    pub windows: ::prost::alloc::vec::Vec<WindowInfo>,
    #[prost(string, tag = "5")]
    pub text_content: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub screenshot_available: bool,
    #[prost(string, tag = "7")]
    pub error: ::prost::alloc::string::String,
}
/// Decision request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecideRequest {
    #[prost(string, tag = "1")]
    pub observation_id: ::prost::alloc::string::String,
}
/// Decision response action
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Action {
    /// "click", "type", "screenshot"
    #[prost(string, tag = "1")]
    pub action_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub x: i32,
    #[prost(int32, tag = "4")]
    pub y: i32,
    #[prost(string, tag = "5")]
    pub text: ::prost::alloc::string::String,
    #[prost(float, tag = "6")]
    pub confidence: f32,
    #[prost(string, tag = "7")]
    pub action_id: ::prost::alloc::string::String,
}
/// Decision response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecideResponse {
    #[prost(string, tag = "1")]
    pub observation_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub action: ::core::option::Option<Action>,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
/// Act request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub action: ::core::option::Option<Action>,
}
/// Act response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub action_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub screenshot: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
/// Verify request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub action: ::core::option::Option<Action>,
    #[prost(string, tag = "3")]
    pub expected_state: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub actual_state: ::prost::alloc::string::String,
}
/// Verify response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyResponse {
    #[prost(bool, tag = "1")]
    pub verified: bool,
    #[prost(float, tag = "2")]
    pub confidence: f32,
    #[prost(string, tag = "3")]
    pub notes: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
/// Recover request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecoverRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub failure_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub context: ::prost::alloc::string::String,
}
/// Recovery response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecoveryResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub recovery_action: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub notes: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
/// Close session request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CloseSessionRequest {
    #[prost(string, tag = "1")]
    pub session_id: ::prost::alloc::string::String,
}
/// Close session response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CloseSessionResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod desktop_automation_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Desktop automation service for Windows UI automation
    #[derive(Debug, Clone)]
    pub struct DesktopAutomationClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl DesktopAutomationClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> DesktopAutomationClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> DesktopAutomationClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            DesktopAutomationClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Capture screen region
        pub async fn screen_capture(
            &mut self,
            request: impl tonic::IntoRequest<super::ScreenCaptureRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ScreenCaptureResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/desktop_protocol.DesktopAutomation/ScreenCapture",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "desktop_protocol.DesktopAutomation",
                        "ScreenCapture",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// OCR screen region
        pub async fn ocr_screen(
            &mut self,
            request: impl tonic::IntoRequest<super::OcrScreenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OcrScreenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/desktop_protocol.DesktopAutomation/OcrScreen",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("desktop_protocol.DesktopAutomation", "OcrScreen"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Find window by title
        pub async fn find_window(
            &mut self,
            request: impl tonic::IntoRequest<super::FindWindowRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FindWindowResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/desktop_protocol.DesktopAutomation/FindWindow",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("desktop_protocol.DesktopAutomation", "FindWindow"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Click at coordinates
        pub async fn click(
            &mut self,
            request: impl tonic::IntoRequest<super::ClickRequest>,
        ) -> std::result::Result<tonic::Response<super::ClickResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/desktop_protocol.DesktopAutomation/Click",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("desktop_protocol.DesktopAutomation", "Click"));
            self.inner.unary(req, path, codec).await
        }
        /// Type text
        pub async fn r#type(
            &mut self,
            request: impl tonic::IntoRequest<super::TypeRequest>,
        ) -> std::result::Result<tonic::Response<super::TypeResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/desktop_protocol.DesktopAutomation/Type",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("desktop_protocol.DesktopAutomation", "Type"));
            self.inner.unary(req, path, codec).await
        }
        /// Observe desktop state
        pub async fn observe(
            &mut self,
            request: impl tonic::IntoRequest<super::ObserveRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ObserveResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/desktop_protocol.DesktopAutomation/Observe",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("desktop_protocol.DesktopAutomation", "Observe"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Make decision based on observation
        pub async fn decide(
            &mut self,
            request: impl tonic::IntoRequest<super::DecideRequest>,
        ) -> std::result::Result<tonic::Response<super::DecideResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/desktop_protocol.DesktopAutomation/Decide",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("desktop_protocol.DesktopAutomation", "Decide"));
            self.inner.unary(req, path, codec).await
        }
        /// Execute action
        pub async fn act(
            &mut self,
            request: impl tonic::IntoRequest<super::ActRequest>,
        ) -> std::result::Result<tonic::Response<super::ActResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/desktop_protocol.DesktopAutomation/Act",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("desktop_protocol.DesktopAutomation", "Act"));
            self.inner.unary(req, path, codec).await
        }
        /// Verify action result
        pub async fn verify(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyRequest>,
        ) -> std::result::Result<tonic::Response<super::VerifyResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/desktop_protocol.DesktopAutomation/Verify",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("desktop_protocol.DesktopAutomation", "Verify"));
            self.inner.unary(req, path, codec).await
        }
        /// Recover from failure
        pub async fn recover(
            &mut self,
            request: impl tonic::IntoRequest<super::RecoverRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RecoveryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/desktop_protocol.DesktopAutomation/Recover",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("desktop_protocol.DesktopAutomation", "Recover"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Close session
        pub async fn close_session(
            &mut self,
            request: impl tonic::IntoRequest<super::CloseSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CloseSessionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/desktop_protocol.DesktopAutomation/CloseSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("desktop_protocol.DesktopAutomation", "CloseSession"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod desktop_automation_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with DesktopAutomationServer.
    #[async_trait]
    pub trait DesktopAutomation: Send + Sync + 'static {
        /// Capture screen region
        async fn screen_capture(
            &self,
            request: tonic::Request<super::ScreenCaptureRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ScreenCaptureResponse>,
            tonic::Status,
        >;
        /// OCR screen region
        async fn ocr_screen(
            &self,
            request: tonic::Request<super::OcrScreenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::OcrScreenResponse>,
            tonic::Status,
        >;
        /// Find window by title
        async fn find_window(
            &self,
            request: tonic::Request<super::FindWindowRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FindWindowResponse>,
            tonic::Status,
        >;
        /// Click at coordinates
        async fn click(
            &self,
            request: tonic::Request<super::ClickRequest>,
        ) -> std::result::Result<tonic::Response<super::ClickResponse>, tonic::Status>;
        /// Type text
        async fn r#type(
            &self,
            request: tonic::Request<super::TypeRequest>,
        ) -> std::result::Result<tonic::Response<super::TypeResponse>, tonic::Status>;
        /// Observe desktop state
        async fn observe(
            &self,
            request: tonic::Request<super::ObserveRequest>,
        ) -> std::result::Result<tonic::Response<super::ObserveResponse>, tonic::Status>;
        /// Make decision based on observation
        async fn decide(
            &self,
            request: tonic::Request<super::DecideRequest>,
        ) -> std::result::Result<tonic::Response<super::DecideResponse>, tonic::Status>;
        /// Execute action
        async fn act(
            &self,
            request: tonic::Request<super::ActRequest>,
        ) -> std::result::Result<tonic::Response<super::ActResponse>, tonic::Status>;
        /// Verify action result
        async fn verify(
            &self,
            request: tonic::Request<super::VerifyRequest>,
        ) -> std::result::Result<tonic::Response<super::VerifyResponse>, tonic::Status>;
        /// Recover from failure
        async fn recover(
            &self,
            request: tonic::Request<super::RecoverRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RecoveryResponse>,
            tonic::Status,
        >;
        /// Close session
        async fn close_session(
            &self,
            request: tonic::Request<super::CloseSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CloseSessionResponse>,
            tonic::Status,
        >;
    }
    /// Desktop automation service for Windows UI automation
    #[derive(Debug)]
    pub struct DesktopAutomationServer<T: DesktopAutomation> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: DesktopAutomation> DesktopAutomationServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for DesktopAutomationServer<T>
    where
        T: DesktopAutomation,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/desktop_protocol.DesktopAutomation/ScreenCapture" => {
                    #[allow(non_camel_case_types)]
                    struct ScreenCaptureSvc<T: DesktopAutomation>(pub Arc<T>);
                    impl<
                        T: DesktopAutomation,
                    > tonic::server::UnaryService<super::ScreenCaptureRequest>
                    for ScreenCaptureSvc<T> {
                        type Response = super::ScreenCaptureResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ScreenCaptureRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DesktopAutomation>::screen_capture(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ScreenCaptureSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/desktop_protocol.DesktopAutomation/OcrScreen" => {
                    #[allow(non_camel_case_types)]
                    struct OcrScreenSvc<T: DesktopAutomation>(pub Arc<T>);
                    impl<
                        T: DesktopAutomation,
                    > tonic::server::UnaryService<super::OcrScreenRequest>
                    for OcrScreenSvc<T> {
                        type Response = super::OcrScreenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OcrScreenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DesktopAutomation>::ocr_screen(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = OcrScreenSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/desktop_protocol.DesktopAutomation/FindWindow" => {
                    #[allow(non_camel_case_types)]
                    struct FindWindowSvc<T: DesktopAutomation>(pub Arc<T>);
                    impl<
                        T: DesktopAutomation,
                    > tonic::server::UnaryService<super::FindWindowRequest>
                    for FindWindowSvc<T> {
                        type Response = super::FindWindowResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FindWindowRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DesktopAutomation>::find_window(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = FindWindowSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/desktop_protocol.DesktopAutomation/Click" => {
                    #[allow(non_camel_case_types)]
                    struct ClickSvc<T: DesktopAutomation>(pub Arc<T>);
                    impl<
                        T: DesktopAutomation,
                    > tonic::server::UnaryService<super::ClickRequest> for ClickSvc<T> {
                        type Response = super::ClickResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ClickRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DesktopAutomation>::click(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ClickSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/desktop_protocol.DesktopAutomation/Type" => {
                    #[allow(non_camel_case_types)]
                    struct TypeSvc<T: DesktopAutomation>(pub Arc<T>);
                    impl<
                        T: DesktopAutomation,
                    > tonic::server::UnaryService<super::TypeRequest> for TypeSvc<T> {
                        type Response = super::TypeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TypeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DesktopAutomation>::r#type(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = TypeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/desktop_protocol.DesktopAutomation/Observe" => {
                    #[allow(non_camel_case_types)]
                    struct ObserveSvc<T: DesktopAutomation>(pub Arc<T>);
                    impl<
                        T: DesktopAutomation,
                    > tonic::server::UnaryService<super::ObserveRequest>
                    for ObserveSvc<T> {
                        type Response = super::ObserveResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ObserveRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DesktopAutomation>::observe(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ObserveSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/desktop_protocol.DesktopAutomation/Decide" => {
                    #[allow(non_camel_case_types)]
                    struct DecideSvc<T: DesktopAutomation>(pub Arc<T>);
                    impl<
                        T: DesktopAutomation,
                    > tonic::server::UnaryService<super::DecideRequest>
                    for DecideSvc<T> {
                        type Response = super::DecideResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DecideRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DesktopAutomation>::decide(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = DecideSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/desktop_protocol.DesktopAutomation/Act" => {
                    #[allow(non_camel_case_types)]
                    struct ActSvc<T: DesktopAutomation>(pub Arc<T>);
                    impl<
                        T: DesktopAutomation,
                    > tonic::server::UnaryService<super::ActRequest> for ActSvc<T> {
                        type Response = super::ActResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ActRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DesktopAutomation>::act(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ActSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/desktop_protocol.DesktopAutomation/Verify" => {
                    #[allow(non_camel_case_types)]
                    struct VerifySvc<T: DesktopAutomation>(pub Arc<T>);
                    impl<
                        T: DesktopAutomation,
                    > tonic::server::UnaryService<super::VerifyRequest>
                    for VerifySvc<T> {
                        type Response = super::VerifyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::VerifyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DesktopAutomation>::verify(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = VerifySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/desktop_protocol.DesktopAutomation/Recover" => {
                    #[allow(non_camel_case_types)]
                    struct RecoverSvc<T: DesktopAutomation>(pub Arc<T>);
                    impl<
                        T: DesktopAutomation,
                    > tonic::server::UnaryService<super::RecoverRequest>
                    for RecoverSvc<T> {
                        type Response = super::RecoveryResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RecoverRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DesktopAutomation>::recover(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = RecoverSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/desktop_protocol.DesktopAutomation/CloseSession" => {
                    #[allow(non_camel_case_types)]
                    struct CloseSessionSvc<T: DesktopAutomation>(pub Arc<T>);
                    impl<
                        T: DesktopAutomation,
                    > tonic::server::UnaryService<super::CloseSessionRequest>
                    for CloseSessionSvc<T> {
                        type Response = super::CloseSessionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CloseSessionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as DesktopAutomation>::close_session(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = CloseSessionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: DesktopAutomation> Clone for DesktopAutomationServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: DesktopAutomation> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: DesktopAutomation> tonic::server::NamedService
    for DesktopAutomationServer<T> {
        const NAME: &'static str = "desktop_protocol.DesktopAutomation";
    }
}
