# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import runtime_pb2 as runtime__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub(object):
    """RuntimeService is the primary gRPC interface between Go supervisor and Python runtime
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/runtime.RuntimeService/CreateTask',
                request_serializer=runtime__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=runtime__pb2.CreateTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/runtime.RuntimeService/GetTask',
                request_serializer=runtime__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=runtime__pb2.GetTaskResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/runtime.RuntimeService/CancelTask',
                request_serializer=runtime__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=runtime__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/runtime.RuntimeService/ListTasks',
                request_serializer=runtime__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=runtime__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.StreamTaskEvents = channel.unary_stream(
                '/runtime.RuntimeService/StreamTaskEvents',
                request_serializer=runtime__pb2.TaskEventRequest.SerializeToString,
                response_deserializer=runtime__pb2.TaskEvent.FromString,
                _registered_method=True)
        self.ApproveTask = channel.unary_unary(
                '/runtime.RuntimeService/ApproveTask',
                request_serializer=runtime__pb2.ApproveTaskRequest.SerializeToString,
                response_deserializer=runtime__pb2.ApproveTaskResponse.FromString,
                _registered_method=True)
        self.RejectTask = channel.unary_unary(
                '/runtime.RuntimeService/RejectTask',
                request_serializer=runtime__pb2.RejectTaskRequest.SerializeToString,
                response_deserializer=runtime__pb2.RejectTaskResponse.FromString,
                _registered_method=True)
        self.GetRuntimeStatus = channel.unary_unary(
                '/runtime.RuntimeService/GetRuntimeStatus',
                request_serializer=runtime__pb2.GetRuntimeStatusRequest.SerializeToString,
                response_deserializer=runtime__pb2.RuntimeStatus.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/runtime.RuntimeService/Shutdown',
                request_serializer=runtime__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=runtime__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/runtime.RuntimeService/HealthCheck',
                request_serializer=runtime__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=runtime__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/runtime.RuntimeService/GetConfig',
                request_serializer=runtime__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=runtime__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/runtime.RuntimeService/SetConfig',
                request_serializer=runtime__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=runtime__pb2.SetConfigResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """RuntimeService is the primary gRPC interface between Go supervisor and Python runtime
    """

    def CreateTask(self, request, context):
        """Task Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTaskEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveTask(self, request, context):
        """Task Actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeStatus(self, request, context):
        """Runtime Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health Check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=runtime__pb2.CreateTaskRequest.FromString,
                    response_serializer=runtime__pb2.CreateTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=runtime__pb2.GetTaskRequest.FromString,
                    response_serializer=runtime__pb2.GetTaskResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=runtime__pb2.CancelTaskRequest.FromString,
                    response_serializer=runtime__pb2.CancelTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=runtime__pb2.ListTasksRequest.FromString,
                    response_serializer=runtime__pb2.ListTasksResponse.SerializeToString,
            ),
            'StreamTaskEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTaskEvents,
                    request_deserializer=runtime__pb2.TaskEventRequest.FromString,
                    response_serializer=runtime__pb2.TaskEvent.SerializeToString,
            ),
            'ApproveTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveTask,
                    request_deserializer=runtime__pb2.ApproveTaskRequest.FromString,
                    response_serializer=runtime__pb2.ApproveTaskResponse.SerializeToString,
            ),
            'RejectTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectTask,
                    request_deserializer=runtime__pb2.RejectTaskRequest.FromString,
                    response_serializer=runtime__pb2.RejectTaskResponse.SerializeToString,
            ),
            'GetRuntimeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeStatus,
                    request_deserializer=runtime__pb2.GetRuntimeStatusRequest.FromString,
                    response_serializer=runtime__pb2.RuntimeStatus.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=runtime__pb2.ShutdownRequest.FromString,
                    response_serializer=runtime__pb2.ShutdownResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=runtime__pb2.HealthCheckRequest.FromString,
                    response_serializer=runtime__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=runtime__pb2.GetConfigRequest.FromString,
                    response_serializer=runtime__pb2.GetConfigResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=runtime__pb2.SetConfigRequest.FromString,
                    response_serializer=runtime__pb2.SetConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtime.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtime.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """RuntimeService is the primary gRPC interface between Go supervisor and Python runtime
    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.RuntimeService/CreateTask',
            runtime__pb2.CreateTaskRequest.SerializeToString,
            runtime__pb2.CreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.RuntimeService/GetTask',
            runtime__pb2.GetTaskRequest.SerializeToString,
            runtime__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.RuntimeService/CancelTask',
            runtime__pb2.CancelTaskRequest.SerializeToString,
            runtime__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.RuntimeService/ListTasks',
            runtime__pb2.ListTasksRequest.SerializeToString,
            runtime__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/runtime.RuntimeService/StreamTaskEvents',
            runtime__pb2.TaskEventRequest.SerializeToString,
            runtime__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.RuntimeService/ApproveTask',
            runtime__pb2.ApproveTaskRequest.SerializeToString,
            runtime__pb2.ApproveTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.RuntimeService/RejectTask',
            runtime__pb2.RejectTaskRequest.SerializeToString,
            runtime__pb2.RejectTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.RuntimeService/GetRuntimeStatus',
            runtime__pb2.GetRuntimeStatusRequest.SerializeToString,
            runtime__pb2.RuntimeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.RuntimeService/Shutdown',
            runtime__pb2.ShutdownRequest.SerializeToString,
            runtime__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.RuntimeService/HealthCheck',
            runtime__pb2.HealthCheckRequest.SerializeToString,
            runtime__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.RuntimeService/GetConfig',
            runtime__pb2.GetConfigRequest.SerializeToString,
            runtime__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.RuntimeService/SetConfig',
            runtime__pb2.SetConfigRequest.SerializeToString,
            runtime__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
