# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import checkpoint_pb2 as checkpoint__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in checkpoint_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CheckpointServiceStub(object):
    """CheckpointService handles persistent state management via SQLite
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveCheckpoint = channel.unary_unary(
                '/checkpoint.CheckpointService/SaveCheckpoint',
                request_serializer=checkpoint__pb2.SaveCheckpointRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.SaveCheckpointResponse.FromString,
                _registered_method=True)
        self.GetCheckpoint = channel.unary_unary(
                '/checkpoint.CheckpointService/GetCheckpoint',
                request_serializer=checkpoint__pb2.GetCheckpointRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.GetCheckpointResponse.FromString,
                _registered_method=True)
        self.ListCheckpoints = channel.unary_unary(
                '/checkpoint.CheckpointService/ListCheckpoints',
                request_serializer=checkpoint__pb2.ListCheckpointsRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.ListCheckpointsResponse.FromString,
                _registered_method=True)
        self.GetLatestCheckpoint = channel.unary_unary(
                '/checkpoint.CheckpointService/GetLatestCheckpoint',
                request_serializer=checkpoint__pb2.GetLatestCheckpointRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.GetCheckpointResponse.FromString,
                _registered_method=True)
        self.CleanupCheckpoints = channel.unary_unary(
                '/checkpoint.CheckpointService/CleanupCheckpoints',
                request_serializer=checkpoint__pb2.CleanupCheckpointsRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.CleanupCheckpointsResponse.FromString,
                _registered_method=True)
        self.SubscribeCheckpoints = channel.unary_stream(
                '/checkpoint.CheckpointService/SubscribeCheckpoints',
                request_serializer=checkpoint__pb2.SubscribeCheckpointsRequest.SerializeToString,
                response_deserializer=checkpoint__pb2.CheckpointEvent.FromString,
                _registered_method=True)


class CheckpointServiceServicer(object):
    """CheckpointService handles persistent state management via SQLite
    """

    def SaveCheckpoint(self, request, context):
        """Save checkpoint state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpoint(self, request, context):
        """Get checkpoint by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCheckpoints(self, request, context):
        """List checkpoints for a task/thread
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestCheckpoint(self, request, context):
        """Get latest checkpoint for a thread
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupCheckpoints(self, request, context):
        """Delete old checkpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeCheckpoints(self, request, context):
        """Streaming: Subscribe to checkpoint updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckpointServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCheckpoint,
                    request_deserializer=checkpoint__pb2.SaveCheckpointRequest.FromString,
                    response_serializer=checkpoint__pb2.SaveCheckpointResponse.SerializeToString,
            ),
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=checkpoint__pb2.GetCheckpointRequest.FromString,
                    response_serializer=checkpoint__pb2.GetCheckpointResponse.SerializeToString,
            ),
            'ListCheckpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCheckpoints,
                    request_deserializer=checkpoint__pb2.ListCheckpointsRequest.FromString,
                    response_serializer=checkpoint__pb2.ListCheckpointsResponse.SerializeToString,
            ),
            'GetLatestCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestCheckpoint,
                    request_deserializer=checkpoint__pb2.GetLatestCheckpointRequest.FromString,
                    response_serializer=checkpoint__pb2.GetCheckpointResponse.SerializeToString,
            ),
            'CleanupCheckpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupCheckpoints,
                    request_deserializer=checkpoint__pb2.CleanupCheckpointsRequest.FromString,
                    response_serializer=checkpoint__pb2.CleanupCheckpointsResponse.SerializeToString,
            ),
            'SubscribeCheckpoints': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeCheckpoints,
                    request_deserializer=checkpoint__pb2.SubscribeCheckpointsRequest.FromString,
                    response_serializer=checkpoint__pb2.CheckpointEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checkpoint.CheckpointService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('checkpoint.CheckpointService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CheckpointService(object):
    """CheckpointService handles persistent state management via SQLite
    """

    @staticmethod
    def SaveCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkpoint.CheckpointService/SaveCheckpoint',
            checkpoint__pb2.SaveCheckpointRequest.SerializeToString,
            checkpoint__pb2.SaveCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkpoint.CheckpointService/GetCheckpoint',
            checkpoint__pb2.GetCheckpointRequest.SerializeToString,
            checkpoint__pb2.GetCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCheckpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkpoint.CheckpointService/ListCheckpoints',
            checkpoint__pb2.ListCheckpointsRequest.SerializeToString,
            checkpoint__pb2.ListCheckpointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkpoint.CheckpointService/GetLatestCheckpoint',
            checkpoint__pb2.GetLatestCheckpointRequest.SerializeToString,
            checkpoint__pb2.GetCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupCheckpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/checkpoint.CheckpointService/CleanupCheckpoints',
            checkpoint__pb2.CleanupCheckpointsRequest.SerializeToString,
            checkpoint__pb2.CleanupCheckpointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeCheckpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/checkpoint.CheckpointService/SubscribeCheckpoints',
            checkpoint__pb2.SubscribeCheckpointsRequest.SerializeToString,
            checkpoint__pb2.CheckpointEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
