// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/checkpoint.proto

package checkpoint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckpointType int32

const (
	CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED CheckpointType = 0
	CheckpointType_CHECKPOINT_TYPE_LOCAL       CheckpointType = 1 // Local SQLite storage
	CheckpointType_CHECKPOINT_TYPE_MEMORY      CheckpointType = 2 // In-memory (for testing)
)

// Enum value maps for CheckpointType.
var (
	CheckpointType_name = map[int32]string{
		0: "CHECKPOINT_TYPE_UNSPECIFIED",
		1: "CHECKPOINT_TYPE_LOCAL",
		2: "CHECKPOINT_TYPE_MEMORY",
	}
	CheckpointType_value = map[string]int32{
		"CHECKPOINT_TYPE_UNSPECIFIED": 0,
		"CHECKPOINT_TYPE_LOCAL":       1,
		"CHECKPOINT_TYPE_MEMORY":      2,
	}
)

func (x CheckpointType) Enum() *CheckpointType {
	p := new(CheckpointType)
	*p = x
	return p
}

func (x CheckpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_checkpoint_proto_enumTypes[0].Descriptor()
}

func (CheckpointType) Type() protoreflect.EnumType {
	return &file_proto_checkpoint_proto_enumTypes[0]
}

func (x CheckpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointType.Descriptor instead.
func (CheckpointType) EnumDescriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{0}
}

type CheckpointEventType int32

const (
	CheckpointEventType_CHECKPOINT_EVENT_UNSPECIFIED CheckpointEventType = 0
	CheckpointEventType_CHECKPOINT_EVENT_CREATED     CheckpointEventType = 1
	CheckpointEventType_CHECKPOINT_EVENT_UPDATED     CheckpointEventType = 2
	CheckpointEventType_CHECKPOINT_EVENT_DELETED     CheckpointEventType = 3
	CheckpointEventType_CHECKPOINT_EVENT_CLEANUP     CheckpointEventType = 4
)

// Enum value maps for CheckpointEventType.
var (
	CheckpointEventType_name = map[int32]string{
		0: "CHECKPOINT_EVENT_UNSPECIFIED",
		1: "CHECKPOINT_EVENT_CREATED",
		2: "CHECKPOINT_EVENT_UPDATED",
		3: "CHECKPOINT_EVENT_DELETED",
		4: "CHECKPOINT_EVENT_CLEANUP",
	}
	CheckpointEventType_value = map[string]int32{
		"CHECKPOINT_EVENT_UNSPECIFIED": 0,
		"CHECKPOINT_EVENT_CREATED":     1,
		"CHECKPOINT_EVENT_UPDATED":     2,
		"CHECKPOINT_EVENT_DELETED":     3,
		"CHECKPOINT_EVENT_CLEANUP":     4,
	}
)

func (x CheckpointEventType) Enum() *CheckpointEventType {
	p := new(CheckpointEventType)
	*p = x
	return p
}

func (x CheckpointEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_checkpoint_proto_enumTypes[1].Descriptor()
}

func (CheckpointEventType) Type() protoreflect.EnumType {
	return &file_proto_checkpoint_proto_enumTypes[1]
}

func (x CheckpointEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointEventType.Descriptor instead.
func (CheckpointEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{1}
}

// Checkpoint data structure
type Checkpoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ThreadId       string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	CheckpointNs   int64                  `protobuf:"varint,3,opt,name=checkpoint_ns,json=checkpointNs,proto3" json:"checkpoint_ns,omitempty"` // Nanosecond timestamp
	CheckpointType CheckpointType         `protobuf:"varint,4,opt,name=checkpoint_type,json=checkpointType,proto3,enum=checkpoint.CheckpointType" json:"checkpoint_type,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StateBlob      []byte                 `protobuf:"bytes,7,opt,name=state_blob,json=stateBlob,proto3" json:"state_blob,omitempty"`             // Serialized LangGraph state
	ChannelValues  []byte                 `protobuf:"bytes,8,opt,name=channel_values,json=channelValues,proto3" json:"channel_values,omitempty"` // Serialized channel values
	PendingSends   []byte                 `protobuf:"bytes,9,opt,name=pending_sends,json=pendingSends,proto3" json:"pending_sends,omitempty"`
	ParentIds      []string               `protobuf:"bytes,10,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	Metadata       string                 `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	TaskId         string                 `protobuf:"bytes,12,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_proto_checkpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{0}
}

func (x *Checkpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Checkpoint) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Checkpoint) GetCheckpointNs() int64 {
	if x != nil {
		return x.CheckpointNs
	}
	return 0
}

func (x *Checkpoint) GetCheckpointType() CheckpointType {
	if x != nil {
		return x.CheckpointType
	}
	return CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED
}

func (x *Checkpoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Checkpoint) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Checkpoint) GetStateBlob() []byte {
	if x != nil {
		return x.StateBlob
	}
	return nil
}

func (x *Checkpoint) GetChannelValues() []byte {
	if x != nil {
		return x.ChannelValues
	}
	return nil
}

func (x *Checkpoint) GetPendingSends() []byte {
	if x != nil {
		return x.PendingSends
	}
	return nil
}

func (x *Checkpoint) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *Checkpoint) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Checkpoint) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// Save Checkpoint
type SaveCheckpointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ThreadId       string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	CheckpointType CheckpointType         `protobuf:"varint,2,opt,name=checkpoint_type,json=checkpointType,proto3,enum=checkpoint.CheckpointType" json:"checkpoint_type,omitempty"`
	StateBlob      []byte                 `protobuf:"bytes,3,opt,name=state_blob,json=stateBlob,proto3" json:"state_blob,omitempty"`
	ChannelValues  []byte                 `protobuf:"bytes,4,opt,name=channel_values,json=channelValues,proto3" json:"channel_values,omitempty"`
	PendingSends   []byte                 `protobuf:"bytes,5,opt,name=pending_sends,json=pendingSends,proto3" json:"pending_sends,omitempty"`
	ParentIds      []string               `protobuf:"bytes,6,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	Metadata       string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON string
	TaskId         string                 `protobuf:"bytes,8,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SaveCheckpointRequest) Reset() {
	*x = SaveCheckpointRequest{}
	mi := &file_proto_checkpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCheckpointRequest) ProtoMessage() {}

func (x *SaveCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCheckpointRequest.ProtoReflect.Descriptor instead.
func (*SaveCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{1}
}

func (x *SaveCheckpointRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SaveCheckpointRequest) GetCheckpointType() CheckpointType {
	if x != nil {
		return x.CheckpointType
	}
	return CheckpointType_CHECKPOINT_TYPE_UNSPECIFIED
}

func (x *SaveCheckpointRequest) GetStateBlob() []byte {
	if x != nil {
		return x.StateBlob
	}
	return nil
}

func (x *SaveCheckpointRequest) GetChannelValues() []byte {
	if x != nil {
		return x.ChannelValues
	}
	return nil
}

func (x *SaveCheckpointRequest) GetPendingSends() []byte {
	if x != nil {
		return x.PendingSends
	}
	return nil
}

func (x *SaveCheckpointRequest) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *SaveCheckpointRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *SaveCheckpointRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type SaveCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCheckpointResponse) Reset() {
	*x = SaveCheckpointResponse{}
	mi := &file_proto_checkpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCheckpointResponse) ProtoMessage() {}

func (x *SaveCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCheckpointResponse.ProtoReflect.Descriptor instead.
func (*SaveCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{2}
}

func (x *SaveCheckpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveCheckpointResponse) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *SaveCheckpointResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Get Checkpoint
type GetCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointRequest) Reset() {
	*x = GetCheckpointRequest{}
	mi := &file_proto_checkpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointRequest) ProtoMessage() {}

func (x *GetCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointRequest.ProtoReflect.Descriptor instead.
func (*GetCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{3}
}

func (x *GetCheckpointRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type GetCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointResponse) Reset() {
	*x = GetCheckpointResponse{}
	mi := &file_proto_checkpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointResponse) ProtoMessage() {}

func (x *GetCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointResponse.ProtoReflect.Descriptor instead.
func (*GetCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{4}
}

func (x *GetCheckpointResponse) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *GetCheckpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCheckpointResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// List Checkpoints
type ListCheckpointsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ThreadId        string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	IncludeMetadata bool                   `protobuf:"varint,4,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListCheckpointsRequest) Reset() {
	*x = ListCheckpointsRequest{}
	mi := &file_proto_checkpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCheckpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCheckpointsRequest) ProtoMessage() {}

func (x *ListCheckpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCheckpointsRequest.ProtoReflect.Descriptor instead.
func (*ListCheckpointsRequest) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{5}
}

func (x *ListCheckpointsRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ListCheckpointsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCheckpointsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCheckpointsRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

type ListCheckpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoints   []*Checkpoint          `protobuf:"bytes,1,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCheckpointsResponse) Reset() {
	*x = ListCheckpointsResponse{}
	mi := &file_proto_checkpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCheckpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCheckpointsResponse) ProtoMessage() {}

func (x *ListCheckpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCheckpointsResponse.ProtoReflect.Descriptor instead.
func (*ListCheckpointsResponse) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{6}
}

func (x *ListCheckpointsResponse) GetCheckpoints() []*Checkpoint {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

func (x *ListCheckpointsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListCheckpointsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListCheckpointsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Get Latest Checkpoint
type GetLatestCheckpointRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ThreadId        string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	IncludeMetadata bool                   `protobuf:"varint,2,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLatestCheckpointRequest) Reset() {
	*x = GetLatestCheckpointRequest{}
	mi := &file_proto_checkpoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestCheckpointRequest) ProtoMessage() {}

func (x *GetLatestCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestCheckpointRequest.ProtoReflect.Descriptor instead.
func (*GetLatestCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{7}
}

func (x *GetLatestCheckpointRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *GetLatestCheckpointRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

// Cleanup
type CleanupCheckpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`                   // Empty for all threads
	KeepCount     int32                  `protobuf:"varint,2,opt,name=keep_count,json=keepCount,proto3" json:"keep_count,omitempty"`               // Keep N most recent checkpoints
	OlderThanDays int32                  `protobuf:"varint,3,opt,name=older_than_days,json=olderThanDays,proto3" json:"older_than_days,omitempty"` // Delete checkpoints older than N days
	DryRun        bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`                        // Don't actually delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupCheckpointsRequest) Reset() {
	*x = CleanupCheckpointsRequest{}
	mi := &file_proto_checkpoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupCheckpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupCheckpointsRequest) ProtoMessage() {}

func (x *CleanupCheckpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupCheckpointsRequest.ProtoReflect.Descriptor instead.
func (*CleanupCheckpointsRequest) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{8}
}

func (x *CleanupCheckpointsRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *CleanupCheckpointsRequest) GetKeepCount() int32 {
	if x != nil {
		return x.KeepCount
	}
	return 0
}

func (x *CleanupCheckpointsRequest) GetOlderThanDays() int32 {
	if x != nil {
		return x.OlderThanDays
	}
	return 0
}

func (x *CleanupCheckpointsRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type CleanupCheckpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	DeletedIds    []string               `protobuf:"bytes,2,rep,name=deleted_ids,json=deletedIds,proto3" json:"deleted_ids,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupCheckpointsResponse) Reset() {
	*x = CleanupCheckpointsResponse{}
	mi := &file_proto_checkpoint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupCheckpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupCheckpointsResponse) ProtoMessage() {}

func (x *CleanupCheckpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupCheckpointsResponse.ProtoReflect.Descriptor instead.
func (*CleanupCheckpointsResponse) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{9}
}

func (x *CleanupCheckpointsResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *CleanupCheckpointsResponse) GetDeletedIds() []string {
	if x != nil {
		return x.DeletedIds
	}
	return nil
}

func (x *CleanupCheckpointsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CleanupCheckpointsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Checkpoint Events
type SubscribeCheckpointsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ThreadId       string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"` // Empty for all threads
	IncludeHistory bool                   `protobuf:"varint,2,opt,name=include_history,json=includeHistory,proto3" json:"include_history,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeCheckpointsRequest) Reset() {
	*x = SubscribeCheckpointsRequest{}
	mi := &file_proto_checkpoint_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeCheckpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeCheckpointsRequest) ProtoMessage() {}

func (x *SubscribeCheckpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeCheckpointsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeCheckpointsRequest) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeCheckpointsRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SubscribeCheckpointsRequest) GetIncludeHistory() bool {
	if x != nil {
		return x.IncludeHistory
	}
	return false
}

type CheckpointEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	EventType     CheckpointEventType    `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=checkpoint.CheckpointEventType" json:"event_type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,5,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointEvent) Reset() {
	*x = CheckpointEvent{}
	mi := &file_proto_checkpoint_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointEvent) ProtoMessage() {}

func (x *CheckpointEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointEvent.ProtoReflect.Descriptor instead.
func (*CheckpointEvent) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{11}
}

func (x *CheckpointEvent) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *CheckpointEvent) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *CheckpointEvent) GetEventType() CheckpointEventType {
	if x != nil {
		return x.EventType
	}
	return CheckpointEventType_CHECKPOINT_EVENT_UNSPECIFIED
}

func (x *CheckpointEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CheckpointEvent) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *CheckpointEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Migration support
type MigrationStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion    string                 `protobuf:"bytes,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	AppliedMigrations []string               `protobuf:"bytes,2,rep,name=applied_migrations,json=appliedMigrations,proto3" json:"applied_migrations,omitempty"`
	PendingMigrations []string               `protobuf:"bytes,3,rep,name=pending_migrations,json=pendingMigrations,proto3" json:"pending_migrations,omitempty"`
	MigrationRequired bool                   `protobuf:"varint,4,opt,name=migration_required,json=migrationRequired,proto3" json:"migration_required,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MigrationStatus) Reset() {
	*x = MigrationStatus{}
	mi := &file_proto_checkpoint_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStatus) ProtoMessage() {}

func (x *MigrationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStatus.ProtoReflect.Descriptor instead.
func (*MigrationStatus) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{12}
}

func (x *MigrationStatus) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *MigrationStatus) GetAppliedMigrations() []string {
	if x != nil {
		return x.AppliedMigrations
	}
	return nil
}

func (x *MigrationStatus) GetPendingMigrations() []string {
	if x != nil {
		return x.PendingMigrations
	}
	return nil
}

func (x *MigrationStatus) GetMigrationRequired() bool {
	if x != nil {
		return x.MigrationRequired
	}
	return false
}

type RunMigrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DryRun        bool                   `protobuf:"varint,1,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	TargetVersion string                 `protobuf:"bytes,2,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"` // Empty for latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunMigrationsRequest) Reset() {
	*x = RunMigrationsRequest{}
	mi := &file_proto_checkpoint_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMigrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMigrationsRequest) ProtoMessage() {}

func (x *RunMigrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMigrationsRequest.ProtoReflect.Descriptor instead.
func (*RunMigrationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{13}
}

func (x *RunMigrationsRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *RunMigrationsRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

type RunMigrationsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AppliedCount      int32                  `protobuf:"varint,2,opt,name=applied_count,json=appliedCount,proto3" json:"applied_count,omitempty"`
	AppliedMigrations []string               `protobuf:"bytes,3,rep,name=applied_migrations,json=appliedMigrations,proto3" json:"applied_migrations,omitempty"`
	Error             string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunMigrationsResponse) Reset() {
	*x = RunMigrationsResponse{}
	mi := &file_proto_checkpoint_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunMigrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunMigrationsResponse) ProtoMessage() {}

func (x *RunMigrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunMigrationsResponse.ProtoReflect.Descriptor instead.
func (*RunMigrationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{14}
}

func (x *RunMigrationsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RunMigrationsResponse) GetAppliedCount() int32 {
	if x != nil {
		return x.AppliedCount
	}
	return 0
}

func (x *RunMigrationsResponse) GetAppliedMigrations() []string {
	if x != nil {
		return x.AppliedMigrations
	}
	return nil
}

func (x *RunMigrationsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Health check
type CheckpointHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointHealthRequest) Reset() {
	*x = CheckpointHealthRequest{}
	mi := &file_proto_checkpoint_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointHealthRequest) ProtoMessage() {}

func (x *CheckpointHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckpointHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{15}
}

type CheckpointHealthResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Healthy          bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	TotalCheckpoints int64                  `protobuf:"varint,2,opt,name=total_checkpoints,json=totalCheckpoints,proto3" json:"total_checkpoints,omitempty"`
	TotalSizeBytes   int64                  `protobuf:"varint,3,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	MigrationStatus  *MigrationStatus       `protobuf:"bytes,4,opt,name=migration_status,json=migrationStatus,proto3" json:"migration_status,omitempty"`
	Error            string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckpointHealthResponse) Reset() {
	*x = CheckpointHealthResponse{}
	mi := &file_proto_checkpoint_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointHealthResponse) ProtoMessage() {}

func (x *CheckpointHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_checkpoint_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckpointHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_checkpoint_proto_rawDescGZIP(), []int{16}
}

func (x *CheckpointHealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *CheckpointHealthResponse) GetTotalCheckpoints() int64 {
	if x != nil {
		return x.TotalCheckpoints
	}
	return 0
}

func (x *CheckpointHealthResponse) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *CheckpointHealthResponse) GetMigrationStatus() *MigrationStatus {
	if x != nil {
		return x.MigrationStatus
	}
	return nil
}

func (x *CheckpointHealthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_checkpoint_proto protoreflect.FileDescriptor

const file_proto_checkpoint_proto_rawDesc = "" +
	"\n" +
	"\x16proto/checkpoint.proto\x12\n" +
	"checkpoint\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd8\x03\n" +
	"\n" +
	"Checkpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12#\n" +
	"\rcheckpoint_ns\x18\x03 \x01(\x03R\fcheckpointNs\x12C\n" +
	"\x0fcheckpoint_type\x18\x04 \x01(\x0e2\x1a.checkpoint.CheckpointTypeR\x0echeckpointType\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"state_blob\x18\a \x01(\fR\tstateBlob\x12%\n" +
	"\x0echannel_values\x18\b \x01(\fR\rchannelValues\x12#\n" +
	"\rpending_sends\x18\t \x01(\fR\fpendingSends\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\n" +
	" \x03(\tR\tparentIds\x12\x1a\n" +
	"\bmetadata\x18\v \x01(\tR\bmetadata\x12\x17\n" +
	"\atask_id\x18\f \x01(\tR\x06taskId\"\xb8\x02\n" +
	"\x15SaveCheckpointRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12C\n" +
	"\x0fcheckpoint_type\x18\x02 \x01(\x0e2\x1a.checkpoint.CheckpointTypeR\x0echeckpointType\x12\x1d\n" +
	"\n" +
	"state_blob\x18\x03 \x01(\fR\tstateBlob\x12%\n" +
	"\x0echannel_values\x18\x04 \x01(\fR\rchannelValues\x12#\n" +
	"\rpending_sends\x18\x05 \x01(\fR\fpendingSends\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x06 \x03(\tR\tparentIds\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\x12\x17\n" +
	"\atask_id\x18\b \x01(\tR\x06taskId\"m\n" +
	"\x16SaveCheckpointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\";\n" +
	"\x14GetCheckpointRequest\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\"\x7f\n" +
	"\x15GetCheckpointResponse\x126\n" +
	"\n" +
	"checkpoint\x18\x01 \x01(\v2\x16.checkpoint.CheckpointR\n" +
	"checkpoint\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8e\x01\n" +
	"\x16ListCheckpointsRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12)\n" +
	"\x10include_metadata\x18\x04 \x01(\bR\x0fincludeMetadata\"\xa4\x01\n" +
	"\x17ListCheckpointsResponse\x128\n" +
	"\vcheckpoints\x18\x01 \x03(\v2\x16.checkpoint.CheckpointR\vcheckpoints\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"d\n" +
	"\x1aGetLatestCheckpointRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12)\n" +
	"\x10include_metadata\x18\x02 \x01(\bR\x0fincludeMetadata\"\x98\x01\n" +
	"\x19CleanupCheckpointsRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x1d\n" +
	"\n" +
	"keep_count\x18\x02 \x01(\x05R\tkeepCount\x12&\n" +
	"\x0folder_than_days\x18\x03 \x01(\x05R\rolderThanDays\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\"\x92\x01\n" +
	"\x1aCleanupCheckpointsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\x12\x1f\n" +
	"\vdeleted_ids\x18\x02 \x03(\tR\n" +
	"deletedIds\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"c\n" +
	"\x1bSubscribeCheckpointsRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12'\n" +
	"\x0finclude_history\x18\x02 \x01(\bR\x0eincludeHistory\"\x9b\x02\n" +
	"\x0fCheckpointEvent\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12>\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\x1f.checkpoint.CheckpointEventTypeR\teventType\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x126\n" +
	"\n" +
	"checkpoint\x18\x05 \x01(\v2\x16.checkpoint.CheckpointR\n" +
	"checkpoint\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xc7\x01\n" +
	"\x0fMigrationStatus\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\tR\x0ecurrentVersion\x12-\n" +
	"\x12applied_migrations\x18\x02 \x03(\tR\x11appliedMigrations\x12-\n" +
	"\x12pending_migrations\x18\x03 \x03(\tR\x11pendingMigrations\x12-\n" +
	"\x12migration_required\x18\x04 \x01(\bR\x11migrationRequired\"V\n" +
	"\x14RunMigrationsRequest\x12\x17\n" +
	"\adry_run\x18\x01 \x01(\bR\x06dryRun\x12%\n" +
	"\x0etarget_version\x18\x02 \x01(\tR\rtargetVersion\"\x9b\x01\n" +
	"\x15RunMigrationsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rapplied_count\x18\x02 \x01(\x05R\fappliedCount\x12-\n" +
	"\x12applied_migrations\x18\x03 \x03(\tR\x11appliedMigrations\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x19\n" +
	"\x17CheckpointHealthRequest\"\xe9\x01\n" +
	"\x18CheckpointHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12+\n" +
	"\x11total_checkpoints\x18\x02 \x01(\x03R\x10totalCheckpoints\x12(\n" +
	"\x10total_size_bytes\x18\x03 \x01(\x03R\x0etotalSizeBytes\x12F\n" +
	"\x10migration_status\x18\x04 \x01(\v2\x1b.checkpoint.MigrationStatusR\x0fmigrationStatus\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error*h\n" +
	"\x0eCheckpointType\x12\x1f\n" +
	"\x1bCHECKPOINT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CHECKPOINT_TYPE_LOCAL\x10\x01\x12\x1a\n" +
	"\x16CHECKPOINT_TYPE_MEMORY\x10\x02*\xaf\x01\n" +
	"\x13CheckpointEventType\x12 \n" +
	"\x1cCHECKPOINT_EVENT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CHECKPOINT_EVENT_CREATED\x10\x01\x12\x1c\n" +
	"\x18CHECKPOINT_EVENT_UPDATED\x10\x02\x12\x1c\n" +
	"\x18CHECKPOINT_EVENT_DELETED\x10\x03\x12\x1c\n" +
	"\x18CHECKPOINT_EVENT_CLEANUP\x10\x042\xc5\x04\n" +
	"\x11CheckpointService\x12W\n" +
	"\x0eSaveCheckpoint\x12!.checkpoint.SaveCheckpointRequest\x1a\".checkpoint.SaveCheckpointResponse\x12T\n" +
	"\rGetCheckpoint\x12 .checkpoint.GetCheckpointRequest\x1a!.checkpoint.GetCheckpointResponse\x12Z\n" +
	"\x0fListCheckpoints\x12\".checkpoint.ListCheckpointsRequest\x1a#.checkpoint.ListCheckpointsResponse\x12`\n" +
	"\x13GetLatestCheckpoint\x12&.checkpoint.GetLatestCheckpointRequest\x1a!.checkpoint.GetCheckpointResponse\x12c\n" +
	"\x12CleanupCheckpoints\x12%.checkpoint.CleanupCheckpointsRequest\x1a&.checkpoint.CleanupCheckpointsResponse\x12^\n" +
	"\x14SubscribeCheckpoints\x12'.checkpoint.SubscribeCheckpointsRequest\x1a\x1b.checkpoint.CheckpointEvent0\x01B0Z.github.com/AgentOS/supervisor/proto/checkpointb\x06proto3"

var (
	file_proto_checkpoint_proto_rawDescOnce sync.Once
	file_proto_checkpoint_proto_rawDescData []byte
)

func file_proto_checkpoint_proto_rawDescGZIP() []byte {
	file_proto_checkpoint_proto_rawDescOnce.Do(func() {
		file_proto_checkpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_checkpoint_proto_rawDesc), len(file_proto_checkpoint_proto_rawDesc)))
	})
	return file_proto_checkpoint_proto_rawDescData
}

var file_proto_checkpoint_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_checkpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_checkpoint_proto_goTypes = []any{
	(CheckpointType)(0),                 // 0: checkpoint.CheckpointType
	(CheckpointEventType)(0),            // 1: checkpoint.CheckpointEventType
	(*Checkpoint)(nil),                  // 2: checkpoint.Checkpoint
	(*SaveCheckpointRequest)(nil),       // 3: checkpoint.SaveCheckpointRequest
	(*SaveCheckpointResponse)(nil),      // 4: checkpoint.SaveCheckpointResponse
	(*GetCheckpointRequest)(nil),        // 5: checkpoint.GetCheckpointRequest
	(*GetCheckpointResponse)(nil),       // 6: checkpoint.GetCheckpointResponse
	(*ListCheckpointsRequest)(nil),      // 7: checkpoint.ListCheckpointsRequest
	(*ListCheckpointsResponse)(nil),     // 8: checkpoint.ListCheckpointsResponse
	(*GetLatestCheckpointRequest)(nil),  // 9: checkpoint.GetLatestCheckpointRequest
	(*CleanupCheckpointsRequest)(nil),   // 10: checkpoint.CleanupCheckpointsRequest
	(*CleanupCheckpointsResponse)(nil),  // 11: checkpoint.CleanupCheckpointsResponse
	(*SubscribeCheckpointsRequest)(nil), // 12: checkpoint.SubscribeCheckpointsRequest
	(*CheckpointEvent)(nil),             // 13: checkpoint.CheckpointEvent
	(*MigrationStatus)(nil),             // 14: checkpoint.MigrationStatus
	(*RunMigrationsRequest)(nil),        // 15: checkpoint.RunMigrationsRequest
	(*RunMigrationsResponse)(nil),       // 16: checkpoint.RunMigrationsResponse
	(*CheckpointHealthRequest)(nil),     // 17: checkpoint.CheckpointHealthRequest
	(*CheckpointHealthResponse)(nil),    // 18: checkpoint.CheckpointHealthResponse
	(*timestamppb.Timestamp)(nil),       // 19: google.protobuf.Timestamp
}
var file_proto_checkpoint_proto_depIdxs = []int32{
	0,  // 0: checkpoint.Checkpoint.checkpoint_type:type_name -> checkpoint.CheckpointType
	19, // 1: checkpoint.Checkpoint.created_at:type_name -> google.protobuf.Timestamp
	19, // 2: checkpoint.Checkpoint.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: checkpoint.SaveCheckpointRequest.checkpoint_type:type_name -> checkpoint.CheckpointType
	2,  // 4: checkpoint.GetCheckpointResponse.checkpoint:type_name -> checkpoint.Checkpoint
	2,  // 5: checkpoint.ListCheckpointsResponse.checkpoints:type_name -> checkpoint.Checkpoint
	1,  // 6: checkpoint.CheckpointEvent.event_type:type_name -> checkpoint.CheckpointEventType
	19, // 7: checkpoint.CheckpointEvent.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 8: checkpoint.CheckpointEvent.checkpoint:type_name -> checkpoint.Checkpoint
	14, // 9: checkpoint.CheckpointHealthResponse.migration_status:type_name -> checkpoint.MigrationStatus
	3,  // 10: checkpoint.CheckpointService.SaveCheckpoint:input_type -> checkpoint.SaveCheckpointRequest
	5,  // 11: checkpoint.CheckpointService.GetCheckpoint:input_type -> checkpoint.GetCheckpointRequest
	7,  // 12: checkpoint.CheckpointService.ListCheckpoints:input_type -> checkpoint.ListCheckpointsRequest
	9,  // 13: checkpoint.CheckpointService.GetLatestCheckpoint:input_type -> checkpoint.GetLatestCheckpointRequest
	10, // 14: checkpoint.CheckpointService.CleanupCheckpoints:input_type -> checkpoint.CleanupCheckpointsRequest
	12, // 15: checkpoint.CheckpointService.SubscribeCheckpoints:input_type -> checkpoint.SubscribeCheckpointsRequest
	4,  // 16: checkpoint.CheckpointService.SaveCheckpoint:output_type -> checkpoint.SaveCheckpointResponse
	6,  // 17: checkpoint.CheckpointService.GetCheckpoint:output_type -> checkpoint.GetCheckpointResponse
	8,  // 18: checkpoint.CheckpointService.ListCheckpoints:output_type -> checkpoint.ListCheckpointsResponse
	6,  // 19: checkpoint.CheckpointService.GetLatestCheckpoint:output_type -> checkpoint.GetCheckpointResponse
	11, // 20: checkpoint.CheckpointService.CleanupCheckpoints:output_type -> checkpoint.CleanupCheckpointsResponse
	13, // 21: checkpoint.CheckpointService.SubscribeCheckpoints:output_type -> checkpoint.CheckpointEvent
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_checkpoint_proto_init() }
func file_proto_checkpoint_proto_init() {
	if File_proto_checkpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_checkpoint_proto_rawDesc), len(file_proto_checkpoint_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_checkpoint_proto_goTypes,
		DependencyIndexes: file_proto_checkpoint_proto_depIdxs,
		EnumInfos:         file_proto_checkpoint_proto_enumTypes,
		MessageInfos:      file_proto_checkpoint_proto_msgTypes,
	}.Build()
	File_proto_checkpoint_proto = out.File
	file_proto_checkpoint_proto_goTypes = nil
	file_proto_checkpoint_proto_depIdxs = nil
}
