// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: proto/checkpoint.proto

package checkpoint

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CheckpointService_SaveCheckpoint_FullMethodName       = "/checkpoint.CheckpointService/SaveCheckpoint"
	CheckpointService_GetCheckpoint_FullMethodName        = "/checkpoint.CheckpointService/GetCheckpoint"
	CheckpointService_ListCheckpoints_FullMethodName      = "/checkpoint.CheckpointService/ListCheckpoints"
	CheckpointService_GetLatestCheckpoint_FullMethodName  = "/checkpoint.CheckpointService/GetLatestCheckpoint"
	CheckpointService_CleanupCheckpoints_FullMethodName   = "/checkpoint.CheckpointService/CleanupCheckpoints"
	CheckpointService_SubscribeCheckpoints_FullMethodName = "/checkpoint.CheckpointService/SubscribeCheckpoints"
)

// CheckpointServiceClient is the client API for CheckpointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CheckpointService handles persistent state management via SQLite
type CheckpointServiceClient interface {
	// Save checkpoint state
	SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error)
	// Get checkpoint by ID
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error)
	// List checkpoints for a task/thread
	ListCheckpoints(ctx context.Context, in *ListCheckpointsRequest, opts ...grpc.CallOption) (*ListCheckpointsResponse, error)
	// Get latest checkpoint for a thread
	GetLatestCheckpoint(ctx context.Context, in *GetLatestCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error)
	// Delete old checkpoints
	CleanupCheckpoints(ctx context.Context, in *CleanupCheckpointsRequest, opts ...grpc.CallOption) (*CleanupCheckpointsResponse, error)
	// Streaming: Subscribe to checkpoint updates
	SubscribeCheckpoints(ctx context.Context, in *SubscribeCheckpointsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CheckpointEvent], error)
}

type checkpointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckpointServiceClient(cc grpc.ClientConnInterface) CheckpointServiceClient {
	return &checkpointServiceClient{cc}
}

func (c *checkpointServiceClient) SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCheckpointResponse)
	err := c.cc.Invoke(ctx, CheckpointService_SaveCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkpointServiceClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckpointResponse)
	err := c.cc.Invoke(ctx, CheckpointService_GetCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkpointServiceClient) ListCheckpoints(ctx context.Context, in *ListCheckpointsRequest, opts ...grpc.CallOption) (*ListCheckpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCheckpointsResponse)
	err := c.cc.Invoke(ctx, CheckpointService_ListCheckpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkpointServiceClient) GetLatestCheckpoint(ctx context.Context, in *GetLatestCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckpointResponse)
	err := c.cc.Invoke(ctx, CheckpointService_GetLatestCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkpointServiceClient) CleanupCheckpoints(ctx context.Context, in *CleanupCheckpointsRequest, opts ...grpc.CallOption) (*CleanupCheckpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupCheckpointsResponse)
	err := c.cc.Invoke(ctx, CheckpointService_CleanupCheckpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkpointServiceClient) SubscribeCheckpoints(ctx context.Context, in *SubscribeCheckpointsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CheckpointEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CheckpointService_ServiceDesc.Streams[0], CheckpointService_SubscribeCheckpoints_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeCheckpointsRequest, CheckpointEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CheckpointService_SubscribeCheckpointsClient = grpc.ServerStreamingClient[CheckpointEvent]

// CheckpointServiceServer is the server API for CheckpointService service.
// All implementations must embed UnimplementedCheckpointServiceServer
// for forward compatibility.
//
// CheckpointService handles persistent state management via SQLite
type CheckpointServiceServer interface {
	// Save checkpoint state
	SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error)
	// Get checkpoint by ID
	GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error)
	// List checkpoints for a task/thread
	ListCheckpoints(context.Context, *ListCheckpointsRequest) (*ListCheckpointsResponse, error)
	// Get latest checkpoint for a thread
	GetLatestCheckpoint(context.Context, *GetLatestCheckpointRequest) (*GetCheckpointResponse, error)
	// Delete old checkpoints
	CleanupCheckpoints(context.Context, *CleanupCheckpointsRequest) (*CleanupCheckpointsResponse, error)
	// Streaming: Subscribe to checkpoint updates
	SubscribeCheckpoints(*SubscribeCheckpointsRequest, grpc.ServerStreamingServer[CheckpointEvent]) error
	mustEmbedUnimplementedCheckpointServiceServer()
}

// UnimplementedCheckpointServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckpointServiceServer struct{}

func (UnimplementedCheckpointServiceServer) SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCheckpoint not implemented")
}
func (UnimplementedCheckpointServiceServer) GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedCheckpointServiceServer) ListCheckpoints(context.Context, *ListCheckpointsRequest) (*ListCheckpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCheckpoints not implemented")
}
func (UnimplementedCheckpointServiceServer) GetLatestCheckpoint(context.Context, *GetLatestCheckpointRequest) (*GetCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestCheckpoint not implemented")
}
func (UnimplementedCheckpointServiceServer) CleanupCheckpoints(context.Context, *CleanupCheckpointsRequest) (*CleanupCheckpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupCheckpoints not implemented")
}
func (UnimplementedCheckpointServiceServer) SubscribeCheckpoints(*SubscribeCheckpointsRequest, grpc.ServerStreamingServer[CheckpointEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeCheckpoints not implemented")
}
func (UnimplementedCheckpointServiceServer) mustEmbedUnimplementedCheckpointServiceServer() {}
func (UnimplementedCheckpointServiceServer) testEmbeddedByValue()                           {}

// UnsafeCheckpointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckpointServiceServer will
// result in compilation errors.
type UnsafeCheckpointServiceServer interface {
	mustEmbedUnimplementedCheckpointServiceServer()
}

func RegisterCheckpointServiceServer(s grpc.ServiceRegistrar, srv CheckpointServiceServer) {
	// If the following call panics, it indicates UnimplementedCheckpointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckpointService_ServiceDesc, srv)
}

func _CheckpointService_SaveCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckpointServiceServer).SaveCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckpointService_SaveCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckpointServiceServer).SaveCheckpoint(ctx, req.(*SaveCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckpointService_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckpointServiceServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckpointService_GetCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckpointServiceServer).GetCheckpoint(ctx, req.(*GetCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckpointService_ListCheckpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCheckpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckpointServiceServer).ListCheckpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckpointService_ListCheckpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckpointServiceServer).ListCheckpoints(ctx, req.(*ListCheckpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckpointService_GetLatestCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckpointServiceServer).GetLatestCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckpointService_GetLatestCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckpointServiceServer).GetLatestCheckpoint(ctx, req.(*GetLatestCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckpointService_CleanupCheckpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupCheckpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckpointServiceServer).CleanupCheckpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckpointService_CleanupCheckpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckpointServiceServer).CleanupCheckpoints(ctx, req.(*CleanupCheckpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckpointService_SubscribeCheckpoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeCheckpointsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CheckpointServiceServer).SubscribeCheckpoints(m, &grpc.GenericServerStream[SubscribeCheckpointsRequest, CheckpointEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CheckpointService_SubscribeCheckpointsServer = grpc.ServerStreamingServer[CheckpointEvent]

// CheckpointService_ServiceDesc is the grpc.ServiceDesc for CheckpointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckpointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "checkpoint.CheckpointService",
	HandlerType: (*CheckpointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveCheckpoint",
			Handler:    _CheckpointService_SaveCheckpoint_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _CheckpointService_GetCheckpoint_Handler,
		},
		{
			MethodName: "ListCheckpoints",
			Handler:    _CheckpointService_ListCheckpoints_Handler,
		},
		{
			MethodName: "GetLatestCheckpoint",
			Handler:    _CheckpointService_GetLatestCheckpoint_Handler,
		},
		{
			MethodName: "CleanupCheckpoints",
			Handler:    _CheckpointService_CleanupCheckpoints_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeCheckpoints",
			Handler:       _CheckpointService_SubscribeCheckpoints_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/checkpoint.proto",
}
