# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x06worker\"f\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12\x10\n\x08trace_id\x18\x05 \x01(\t\"d\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\x03\" \n\rHealthRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"D\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\x88\x01\n\x0eWorkerExecutor\x12\x38\n\x0b\x45xecuteTask\x12\x13.worker.TaskRequest\x1a\x14.worker.TaskResponse\x12<\n\x0bHealthCheck\x12\x15.worker.HealthRequest\x1a\x16.worker.HealthResponseB%Z#github.com/AgentOS/supervisor/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/AgentOS/supervisor/proto'
  _globals['_TASKREQUEST']._serialized_start=24
  _globals['_TASKREQUEST']._serialized_end=126
  _globals['_TASKRESPONSE']._serialized_start=128
  _globals['_TASKRESPONSE']._serialized_end=228
  _globals['_HEALTHREQUEST']._serialized_start=230
  _globals['_HEALTHREQUEST']._serialized_end=262
  _globals['_HEALTHRESPONSE']._serialized_start=264
  _globals['_HEALTHRESPONSE']._serialized_end=332
  _globals['_WORKEREXECUTOR']._serialized_start=335
  _globals['_WORKEREXECUTOR']._serialized_end=471
# @@protoc_insertion_point(module_scope)
