// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: runtime.proto

package runtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED       TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING           TaskStatus = 1
	TaskStatus_TASK_STATUS_PLANNING          TaskStatus = 2
	TaskStatus_TASK_STATUS_EXECUTING         TaskStatus = 3
	TaskStatus_TASK_STATUS_VERIFYING         TaskStatus = 4
	TaskStatus_TASK_STATUS_AWAITING_APPROVAL TaskStatus = 5
	TaskStatus_TASK_STATUS_COMPLETED         TaskStatus = 6
	TaskStatus_TASK_STATUS_FAILED            TaskStatus = 7
	TaskStatus_TASK_STATUS_CANCELLED         TaskStatus = 8
	TaskStatus_TASK_STATUS_RECOVERING        TaskStatus = 9
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_PLANNING",
		3: "TASK_STATUS_EXECUTING",
		4: "TASK_STATUS_VERIFYING",
		5: "TASK_STATUS_AWAITING_APPROVAL",
		6: "TASK_STATUS_COMPLETED",
		7: "TASK_STATUS_FAILED",
		8: "TASK_STATUS_CANCELLED",
		9: "TASK_STATUS_RECOVERING",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED":       0,
		"TASK_STATUS_PENDING":           1,
		"TASK_STATUS_PLANNING":          2,
		"TASK_STATUS_EXECUTING":         3,
		"TASK_STATUS_VERIFYING":         4,
		"TASK_STATUS_AWAITING_APPROVAL": 5,
		"TASK_STATUS_COMPLETED":         6,
		"TASK_STATUS_FAILED":            7,
		"TASK_STATUS_CANCELLED":         8,
		"TASK_STATUS_RECOVERING":        9,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_TASK_TYPE_SIMPLE      TaskType = 1 // Action V1 fast path
	TaskType_TASK_TYPE_COMPLEX     TaskType = 2 // LangGraph full path
	TaskType_TASK_TYPE_DESKTOP     TaskType = 3 // Desktop automation
	TaskType_TASK_TYPE_AUTONOMOUS  TaskType = 4 // Autonomous mode
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_SIMPLE",
		2: "TASK_TYPE_COMPLEX",
		3: "TASK_TYPE_DESKTOP",
		4: "TASK_TYPE_AUTONOMOUS",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"TASK_TYPE_SIMPLE":      1,
		"TASK_TYPE_COMPLEX":     2,
		"TASK_TYPE_DESKTOP":     3,
		"TASK_TYPE_AUTONOMOUS":  4,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[1].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[1]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{1}
}

type StepStatus int32

const (
	StepStatus_STEP_STATUS_UNSPECIFIED StepStatus = 0
	StepStatus_STEP_STATUS_PENDING     StepStatus = 1
	StepStatus_STEP_STATUS_EXECUTING   StepStatus = 2
	StepStatus_STEP_STATUS_COMPLETED   StepStatus = 3
	StepStatus_STEP_STATUS_FAILED      StepStatus = 4
	StepStatus_STEP_STATUS_SKIPPED     StepStatus = 5
)

// Enum value maps for StepStatus.
var (
	StepStatus_name = map[int32]string{
		0: "STEP_STATUS_UNSPECIFIED",
		1: "STEP_STATUS_PENDING",
		2: "STEP_STATUS_EXECUTING",
		3: "STEP_STATUS_COMPLETED",
		4: "STEP_STATUS_FAILED",
		5: "STEP_STATUS_SKIPPED",
	}
	StepStatus_value = map[string]int32{
		"STEP_STATUS_UNSPECIFIED": 0,
		"STEP_STATUS_PENDING":     1,
		"STEP_STATUS_EXECUTING":   2,
		"STEP_STATUS_COMPLETED":   3,
		"STEP_STATUS_FAILED":      4,
		"STEP_STATUS_SKIPPED":     5,
	}
)

func (x StepStatus) Enum() *StepStatus {
	p := new(StepStatus)
	*p = x
	return p
}

func (x StepStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[2].Descriptor()
}

func (StepStatus) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[2]
}

func (x StepStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepStatus.Descriptor instead.
func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{2}
}

type TaskEventType int32

const (
	TaskEventType_TASK_EVENT_UNSPECIFIED       TaskEventType = 0
	TaskEventType_TASK_EVENT_CREATED           TaskEventType = 1
	TaskEventType_TASK_EVENT_STARTED           TaskEventType = 2
	TaskEventType_TASK_EVENT_STEP_STARTED      TaskEventType = 3
	TaskEventType_TASK_EVENT_STEP_COMPLETED    TaskEventType = 4
	TaskEventType_TASK_EVENT_LOG               TaskEventType = 5
	TaskEventType_TASK_EVENT_PROGRESS          TaskEventType = 6
	TaskEventType_TASK_EVENT_COMPLETED         TaskEventType = 7
	TaskEventType_TASK_EVENT_FAILED            TaskEventType = 8
	TaskEventType_TASK_EVENT_CANCELLED         TaskEventType = 9
	TaskEventType_TASK_EVENT_AWAITING_APPROVAL TaskEventType = 10
)

// Enum value maps for TaskEventType.
var (
	TaskEventType_name = map[int32]string{
		0:  "TASK_EVENT_UNSPECIFIED",
		1:  "TASK_EVENT_CREATED",
		2:  "TASK_EVENT_STARTED",
		3:  "TASK_EVENT_STEP_STARTED",
		4:  "TASK_EVENT_STEP_COMPLETED",
		5:  "TASK_EVENT_LOG",
		6:  "TASK_EVENT_PROGRESS",
		7:  "TASK_EVENT_COMPLETED",
		8:  "TASK_EVENT_FAILED",
		9:  "TASK_EVENT_CANCELLED",
		10: "TASK_EVENT_AWAITING_APPROVAL",
	}
	TaskEventType_value = map[string]int32{
		"TASK_EVENT_UNSPECIFIED":       0,
		"TASK_EVENT_CREATED":           1,
		"TASK_EVENT_STARTED":           2,
		"TASK_EVENT_STEP_STARTED":      3,
		"TASK_EVENT_STEP_COMPLETED":    4,
		"TASK_EVENT_LOG":               5,
		"TASK_EVENT_PROGRESS":          6,
		"TASK_EVENT_COMPLETED":         7,
		"TASK_EVENT_FAILED":            8,
		"TASK_EVENT_CANCELLED":         9,
		"TASK_EVENT_AWAITING_APPROVAL": 10,
	}
)

func (x TaskEventType) Enum() *TaskEventType {
	p := new(TaskEventType)
	*p = x
	return p
}

func (x TaskEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[3].Descriptor()
}

func (TaskEventType) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[3]
}

func (x TaskEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEventType.Descriptor instead.
func (TaskEventType) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{3}
}

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARNING     LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
	LogLevel_LOG_LEVEL_CRITICAL    LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARNING",
		4: "LOG_LEVEL_ERROR",
		5: "LOG_LEVEL_CRITICAL",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARNING":     3,
		"LOG_LEVEL_ERROR":       4,
		"LOG_LEVEL_CRITICAL":    5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[4].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[4]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{4}
}

type RuntimeState int32

const (
	RuntimeState_RUNTIME_STATE_UNSPECIFIED   RuntimeState = 0
	RuntimeState_RUNTIME_STATE_INITIALIZING  RuntimeState = 1
	RuntimeState_RUNTIME_STATE_READY         RuntimeState = 2
	RuntimeState_RUNTIME_STATE_BUSY          RuntimeState = 3
	RuntimeState_RUNTIME_STATE_SHUTTING_DOWN RuntimeState = 4
	RuntimeState_RUNTIME_STATE_ERROR         RuntimeState = 5
)

// Enum value maps for RuntimeState.
var (
	RuntimeState_name = map[int32]string{
		0: "RUNTIME_STATE_UNSPECIFIED",
		1: "RUNTIME_STATE_INITIALIZING",
		2: "RUNTIME_STATE_READY",
		3: "RUNTIME_STATE_BUSY",
		4: "RUNTIME_STATE_SHUTTING_DOWN",
		5: "RUNTIME_STATE_ERROR",
	}
	RuntimeState_value = map[string]int32{
		"RUNTIME_STATE_UNSPECIFIED":   0,
		"RUNTIME_STATE_INITIALIZING":  1,
		"RUNTIME_STATE_READY":         2,
		"RUNTIME_STATE_BUSY":          3,
		"RUNTIME_STATE_SHUTTING_DOWN": 4,
		"RUNTIME_STATE_ERROR":         5,
	}
)

func (x RuntimeState) Enum() *RuntimeState {
	p := new(RuntimeState)
	*p = x
	return p
}

func (x RuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[5].Descriptor()
}

func (RuntimeState) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[5]
}

func (x RuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeState.Descriptor instead.
func (RuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{5}
}

// Task definition
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=runtime.TaskStatus" json:"status,omitempty"`
	Type          TaskType               `protobuf:"varint,4,opt,name=type,proto3,enum=runtime.TaskType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Result        string                 `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	Progress      int32                  `protobuf:"varint,11,opt,name=progress,proto3" json:"progress,omitempty"` // 0-100
	Metadata      map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Task) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Task) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Task) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Task) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Task) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Task) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Create Task
type CreateTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Type            TaskType               `protobuf:"varint,2,opt,name=type,proto3,enum=runtime.TaskType" json:"type,omitempty"`
	RequireApproval bool                   `protobuf:"varint,3,opt,name=require_approval,json=requireApproval,proto3" json:"require_approval,omitempty"`
	TimeoutSeconds  int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ParentTaskId    string                 `protobuf:"bytes,5,opt,name=parent_task_id,json=parentTaskId,proto3" json:"parent_task_id,omitempty"` // For subtasks
	Config          map[string]string      `protobuf:"bytes,6,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CreateTaskRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *CreateTaskRequest) GetRequireApproval() bool {
	if x != nil {
		return x.RequireApproval
	}
	return false
}

func (x *CreateTaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CreateTaskRequest) GetParentTaskId() string {
	if x != nil {
		return x.ParentTaskId
	}
	return ""
}

func (x *CreateTaskRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *CreateTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Get Task
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Steps         []*Step                `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *GetTaskResponse) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *GetTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Step definition
type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolInput     string                 `protobuf:"bytes,3,opt,name=tool_input,json=toolInput,proto3" json:"tool_input,omitempty"`
	ToolOutput    string                 `protobuf:"bytes,4,opt,name=tool_output,json=toolOutput,proto3" json:"tool_output,omitempty"`
	Status        StepStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=runtime.StepStatus" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *Step) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Step) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *Step) GetToolInput() string {
	if x != nil {
		return x.ToolInput
	}
	return ""
}

func (x *Step) GetToolOutput() string {
	if x != nil {
		return x.ToolOutput
	}
	return ""
}

func (x *Step) GetStatus() StepStatus {
	if x != nil {
		return x.Status
	}
	return StepStatus_STEP_STATUS_UNSPECIFIED
}

func (x *Step) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Step) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Step) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Step) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// Cancel Task
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// List Tasks
type ListTasksRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FilterStatus     TaskStatus             `protobuf:"varint,1,opt,name=filter_status,json=filterStatus,proto3,enum=runtime.TaskStatus" json:"filter_status,omitempty"`
	Limit            int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset           int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	IncludeCompleted bool                   `protobuf:"varint,4,opt,name=include_completed,json=includeCompleted,proto3" json:"include_completed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *ListTasksRequest) GetFilterStatus() TaskStatus {
	if x != nil {
		return x.FilterStatus
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTasksRequest) GetIncludeCompleted() bool {
	if x != nil {
		return x.IncludeCompleted
	}
	return false
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListTasksResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Task Events (Streaming)
type TaskEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	IncludeHistory bool                   `protobuf:"varint,2,opt,name=include_history,json=includeHistory,proto3" json:"include_history,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskEventRequest) Reset() {
	*x = TaskEventRequest{}
	mi := &file_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEventRequest) ProtoMessage() {}

func (x *TaskEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEventRequest.ProtoReflect.Descriptor instead.
func (*TaskEventRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *TaskEventRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEventRequest) GetIncludeHistory() bool {
	if x != nil {
		return x.IncludeHistory
	}
	return false
}

type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	EventType     TaskEventType          `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=runtime.TaskEventType" json:"event_type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Task          *Task                  `protobuf:"bytes,4,opt,name=task,proto3" json:"task,omitempty"`
	Step          *Step                  `protobuf:"bytes,5,opt,name=step,proto3" json:"step,omitempty"`
	Log           *LogMessage            `protobuf:"bytes,6,opt,name=log,proto3" json:"log,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetEventType() TaskEventType {
	if x != nil {
		return x.EventType
	}
	return TaskEventType_TASK_EVENT_UNSPECIFIED
}

func (x *TaskEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TaskEvent) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *TaskEvent) GetStep() *Step {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *TaskEvent) GetLog() *LogMessage {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *TaskEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Log Message
type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=runtime.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Context       map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *LogMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogMessage) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogMessage) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *LogMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Approval
type ApproveTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,3,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTaskRequest) Reset() {
	*x = ApproveTaskRequest{}
	mi := &file_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTaskRequest) ProtoMessage() {}

func (x *ApproveTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTaskRequest.ProtoReflect.Descriptor instead.
func (*ApproveTaskRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *ApproveTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ApproveTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ApproveTaskRequest) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type ApproveTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTaskResponse) Reset() {
	*x = ApproveTaskResponse{}
	mi := &file_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTaskResponse) ProtoMessage() {}

func (x *ApproveTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTaskResponse.ProtoReflect.Descriptor instead.
func (*ApproveTaskResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *ApproveTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApproveTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *ApproveTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RejectTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RejectedBy    string                 `protobuf:"bytes,3,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTaskRequest) Reset() {
	*x = RejectTaskRequest{}
	mi := &file_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTaskRequest) ProtoMessage() {}

func (x *RejectTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTaskRequest.ProtoReflect.Descriptor instead.
func (*RejectTaskRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *RejectTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RejectTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RejectTaskRequest) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

type RejectTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTaskResponse) Reset() {
	*x = RejectTaskResponse{}
	mi := &file_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTaskResponse) ProtoMessage() {}

func (x *RejectTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTaskResponse.ProtoReflect.Descriptor instead.
func (*RejectTaskResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *RejectTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RejectTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *RejectTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Runtime Status
type GetRuntimeStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeMetrics bool                   `protobuf:"varint,1,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRuntimeStatusRequest) Reset() {
	*x = GetRuntimeStatusRequest{}
	mi := &file_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeStatusRequest) ProtoMessage() {}

func (x *GetRuntimeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeStatusRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *GetRuntimeStatusRequest) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

type RuntimeStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	State          RuntimeState           `protobuf:"varint,2,opt,name=state,proto3,enum=runtime.RuntimeState" json:"state,omitempty"`
	ActiveTasks    int32                  `protobuf:"varint,3,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	QueuedTasks    int32                  `protobuf:"varint,4,opt,name=queued_tasks,json=queuedTasks,proto3" json:"queued_tasks,omitempty"`
	CompletedTasks int32                  `protobuf:"varint,5,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	FailedTasks    int32                  `protobuf:"varint,6,opt,name=failed_tasks,json=failedTasks,proto3" json:"failed_tasks,omitempty"`
	Metrics        *RuntimeMetrics        `protobuf:"bytes,7,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Uptime         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Config         map[string]string      `protobuf:"bytes,9,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeStatus) Reset() {
	*x = RuntimeStatus{}
	mi := &file_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStatus) ProtoMessage() {}

func (x *RuntimeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStatus.ProtoReflect.Descriptor instead.
func (*RuntimeStatus) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *RuntimeStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RuntimeStatus) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

func (x *RuntimeStatus) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *RuntimeStatus) GetQueuedTasks() int32 {
	if x != nil {
		return x.QueuedTasks
	}
	return 0
}

func (x *RuntimeStatus) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *RuntimeStatus) GetFailedTasks() int32 {
	if x != nil {
		return x.FailedTasks
	}
	return 0
}

func (x *RuntimeStatus) GetMetrics() *RuntimeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *RuntimeStatus) GetUptime() *timestamppb.Timestamp {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *RuntimeStatus) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type RuntimeMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent        float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes       int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	AvgTaskDurationMs float64                `protobuf:"fixed64,3,opt,name=avg_task_duration_ms,json=avgTaskDurationMs,proto3" json:"avg_task_duration_ms,omitempty"`
	TaskSuccessRate   float64                `protobuf:"fixed64,4,opt,name=task_success_rate,json=taskSuccessRate,proto3" json:"task_success_rate,omitempty"`
	TotalToolCalls    int64                  `protobuf:"varint,5,opt,name=total_tool_calls,json=totalToolCalls,proto3" json:"total_tool_calls,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RuntimeMetrics) Reset() {
	*x = RuntimeMetrics{}
	mi := &file_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeMetrics) ProtoMessage() {}

func (x *RuntimeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeMetrics.ProtoReflect.Descriptor instead.
func (*RuntimeMetrics) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *RuntimeMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *RuntimeMetrics) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RuntimeMetrics) GetAvgTaskDurationMs() float64 {
	if x != nil {
		return x.AvgTaskDurationMs
	}
	return 0
}

func (x *RuntimeMetrics) GetTaskSuccessRate() float64 {
	if x != nil {
		return x.TaskSuccessRate
	}
	return 0
}

func (x *RuntimeMetrics) GetTotalToolCalls() int64 {
	if x != nil {
		return x.TotalToolCalls
	}
	return 0
}

// Shutdown
type ShutdownRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Graceful       bool                   `protobuf:"varint,1,opt,name=graceful,proto3" json:"graceful,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{20}
}

func (x *ShutdownRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

func (x *ShutdownRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_runtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{21}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_runtime_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{22}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_runtime_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{23}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Configuration
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // Empty for all config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_runtime_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{24}
}

func (x *GetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_runtime_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{25}
}

func (x *GetConfigResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_runtime_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{26}
}

func (x *SetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_runtime_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{27}
}

func (x *SetConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_runtime_proto protoreflect.FileDescriptor

const file_runtime_proto_rawDesc = "" +
	"\n" +
	"\rruntime.proto\x12\aruntime\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb0\x04\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.runtime.TaskStatusR\x06status\x12%\n" +
	"\x04type\x18\x04 \x01(\x0e2\x11.runtime.TaskTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x16\n" +
	"\x06result\x18\t \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12\x1a\n" +
	"\bprogress\x18\v \x01(\x05R\bprogress\x127\n" +
	"\bmetadata\x18\f \x03(\v2\x1b.runtime.Task.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x02\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.runtime.TaskTypeR\x04type\x12)\n" +
	"\x10require_approval\x18\x03 \x01(\bR\x0frequireApproval\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12$\n" +
	"\x0eparent_task_id\x18\x05 \x01(\tR\fparentTaskId\x12>\n" +
	"\x06config\x18\x06 \x03(\v2&.runtime.CreateTaskRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x12CreateTaskResponse\x12!\n" +
	"\x04task\x18\x01 \x01(\v2\r.runtime.TaskR\x04task\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x89\x01\n" +
	"\x0fGetTaskResponse\x12!\n" +
	"\x04task\x18\x01 \x01(\v2\r.runtime.TaskR\x04task\x12#\n" +
	"\x05steps\x18\x02 \x03(\v2\r.runtime.StepR\x05steps\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xd7\x02\n" +
	"\x04Step\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"tool_input\x18\x03 \x01(\tR\ttoolInput\x12\x1f\n" +
	"\vtool_output\x18\x04 \x01(\tR\n" +
	"toolOutput\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.runtime.StepStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\"D\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"D\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa7\x01\n" +
	"\x10ListTasksRequest\x128\n" +
	"\rfilter_status\x18\x01 \x01(\x0e2\x13.runtime.TaskStatusR\ffilterStatus\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12+\n" +
	"\x11include_completed\x18\x04 \x01(\bR\x10includeCompleted\"s\n" +
	"\x11ListTasksResponse\x12#\n" +
	"\x05tasks\x18\x01 \x03(\v2\r.runtime.TaskR\x05tasks\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"T\n" +
	"\x10TaskEventRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x0finclude_history\x18\x02 \x01(\bR\x0eincludeHistory\"\x98\x02\n" +
	"\tTaskEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x125\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x16.runtime.TaskEventTypeR\teventType\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\x04task\x18\x04 \x01(\v2\r.runtime.TaskR\x04task\x12!\n" +
	"\x04step\x18\x05 \x01(\v2\r.runtime.StepR\x04step\x12%\n" +
	"\x03log\x18\x06 \x01(\v2\x13.runtime.LogMessageR\x03log\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\x99\x02\n" +
	"\n" +
	"LogMessage\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x05level\x18\x02 \x01(\x0e2\x11.runtime.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12:\n" +
	"\acontext\x18\x04 \x03(\v2 .runtime.LogMessage.ContextEntryR\acontext\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x12ApproveTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vapproved_by\x18\x03 \x01(\tR\n" +
	"approvedBy\"h\n" +
	"\x13ApproveTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x04task\x18\x02 \x01(\v2\r.runtime.TaskR\x04task\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"e\n" +
	"\x11RejectTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vrejected_by\x18\x03 \x01(\tR\n" +
	"rejectedBy\"g\n" +
	"\x12RejectTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\x04task\x18\x02 \x01(\v2\r.runtime.TaskR\x04task\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"B\n" +
	"\x17GetRuntimeStatusRequest\x12'\n" +
	"\x0finclude_metrics\x18\x01 \x01(\bR\x0eincludeMetrics\"\xc6\x03\n" +
	"\rRuntimeStatus\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12+\n" +
	"\x05state\x18\x02 \x01(\x0e2\x15.runtime.RuntimeStateR\x05state\x12!\n" +
	"\factive_tasks\x18\x03 \x01(\x05R\vactiveTasks\x12!\n" +
	"\fqueued_tasks\x18\x04 \x01(\x05R\vqueuedTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x05 \x01(\x05R\x0ecompletedTasks\x12!\n" +
	"\ffailed_tasks\x18\x06 \x01(\x05R\vfailedTasks\x121\n" +
	"\ametrics\x18\a \x01(\v2\x17.runtime.RuntimeMetricsR\ametrics\x122\n" +
	"\x06uptime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06uptime\x12:\n" +
	"\x06config\x18\t \x03(\v2\".runtime.RuntimeStatus.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x0eRuntimeMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12/\n" +
	"\x14avg_task_duration_ms\x18\x03 \x01(\x01R\x11avgTaskDurationMs\x12*\n" +
	"\x11task_success_rate\x18\x04 \x01(\x01R\x0ftaskSuccessRate\x12(\n" +
	"\x10total_tool_calls\x18\x05 \x01(\x03R\x0etotalToolCalls\"V\n" +
	"\x0fShutdownRequest\x12\x1a\n" +
	"\bgraceful\x18\x01 \x01(\bR\bgraceful\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"F\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12HealthCheckRequest\"\x83\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"$\n" +
	"\x10GetConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xbe\x01\n" +
	"\x11GetConfigResponse\x12>\n" +
	"\x06config\x18\x01 \x03(\v2&.runtime.GetConfigResponse.ConfigEntryR\x06config\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x10SetConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"C\n" +
	"\x11SetConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\x9f\x02\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14TASK_STATUS_PLANNING\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_EXECUTING\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_VERIFYING\x10\x04\x12!\n" +
	"\x1dTASK_STATUS_AWAITING_APPROVAL\x10\x05\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x06\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\a\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\b\x12\x1a\n" +
	"\x16TASK_STATUS_RECOVERING\x10\t*\x83\x01\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TASK_TYPE_SIMPLE\x10\x01\x12\x15\n" +
	"\x11TASK_TYPE_COMPLEX\x10\x02\x12\x15\n" +
	"\x11TASK_TYPE_DESKTOP\x10\x03\x12\x18\n" +
	"\x14TASK_TYPE_AUTONOMOUS\x10\x04*\xa9\x01\n" +
	"\n" +
	"StepStatus\x12\x1b\n" +
	"\x17STEP_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STEP_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15STEP_STATUS_EXECUTING\x10\x02\x12\x19\n" +
	"\x15STEP_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12STEP_STATUS_FAILED\x10\x04\x12\x17\n" +
	"\x13STEP_STATUS_SKIPPED\x10\x05*\xb1\x02\n" +
	"\rTaskEventType\x12\x1a\n" +
	"\x16TASK_EVENT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_EVENT_CREATED\x10\x01\x12\x16\n" +
	"\x12TASK_EVENT_STARTED\x10\x02\x12\x1b\n" +
	"\x17TASK_EVENT_STEP_STARTED\x10\x03\x12\x1d\n" +
	"\x19TASK_EVENT_STEP_COMPLETED\x10\x04\x12\x12\n" +
	"\x0eTASK_EVENT_LOG\x10\x05\x12\x17\n" +
	"\x13TASK_EVENT_PROGRESS\x10\x06\x12\x18\n" +
	"\x14TASK_EVENT_COMPLETED\x10\a\x12\x15\n" +
	"\x11TASK_EVENT_FAILED\x10\b\x12\x18\n" +
	"\x14TASK_EVENT_CANCELLED\x10\t\x12 \n" +
	"\x1cTASK_EVENT_AWAITING_APPROVAL\x10\n" +
	"*\x92\x01\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x15\n" +
	"\x11LOG_LEVEL_WARNING\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04\x12\x16\n" +
	"\x12LOG_LEVEL_CRITICAL\x10\x05*\xb8\x01\n" +
	"\fRuntimeState\x12\x1d\n" +
	"\x19RUNTIME_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aRUNTIME_STATE_INITIALIZING\x10\x01\x12\x17\n" +
	"\x13RUNTIME_STATE_READY\x10\x02\x12\x16\n" +
	"\x12RUNTIME_STATE_BUSY\x10\x03\x12\x1f\n" +
	"\x1bRUNTIME_STATE_SHUTTING_DOWN\x10\x04\x12\x17\n" +
	"\x13RUNTIME_STATE_ERROR\x10\x052\xd7\x06\n" +
	"\x0eRuntimeService\x12E\n" +
	"\n" +
	"CreateTask\x12\x1a.runtime.CreateTaskRequest\x1a\x1b.runtime.CreateTaskResponse\x12<\n" +
	"\aGetTask\x12\x17.runtime.GetTaskRequest\x1a\x18.runtime.GetTaskResponse\x12E\n" +
	"\n" +
	"CancelTask\x12\x1a.runtime.CancelTaskRequest\x1a\x1b.runtime.CancelTaskResponse\x12B\n" +
	"\tListTasks\x12\x19.runtime.ListTasksRequest\x1a\x1a.runtime.ListTasksResponse\x12C\n" +
	"\x10StreamTaskEvents\x12\x19.runtime.TaskEventRequest\x1a\x12.runtime.TaskEvent0\x01\x12H\n" +
	"\vApproveTask\x12\x1b.runtime.ApproveTaskRequest\x1a\x1c.runtime.ApproveTaskResponse\x12E\n" +
	"\n" +
	"RejectTask\x12\x1a.runtime.RejectTaskRequest\x1a\x1b.runtime.RejectTaskResponse\x12L\n" +
	"\x10GetRuntimeStatus\x12 .runtime.GetRuntimeStatusRequest\x1a\x16.runtime.RuntimeStatus\x12?\n" +
	"\bShutdown\x12\x18.runtime.ShutdownRequest\x1a\x19.runtime.ShutdownResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.runtime.HealthCheckRequest\x1a\x1c.runtime.HealthCheckResponse\x12B\n" +
	"\tGetConfig\x12\x19.runtime.GetConfigRequest\x1a\x1a.runtime.GetConfigResponse\x12B\n" +
	"\tSetConfig\x12\x19.runtime.SetConfigRequest\x1a\x1a.runtime.SetConfigResponseB;Z9github.com/AgentOS/agentos-runtime/internal/proto/runtimeb\x06proto3"

var (
	file_runtime_proto_rawDescOnce sync.Once
	file_runtime_proto_rawDescData []byte
)

func file_runtime_proto_rawDescGZIP() []byte {
	file_runtime_proto_rawDescOnce.Do(func() {
		file_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)))
	})
	return file_runtime_proto_rawDescData
}

var file_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_runtime_proto_goTypes = []any{
	(TaskStatus)(0),                 // 0: runtime.TaskStatus
	(TaskType)(0),                   // 1: runtime.TaskType
	(StepStatus)(0),                 // 2: runtime.StepStatus
	(TaskEventType)(0),              // 3: runtime.TaskEventType
	(LogLevel)(0),                   // 4: runtime.LogLevel
	(RuntimeState)(0),               // 5: runtime.RuntimeState
	(*Task)(nil),                    // 6: runtime.Task
	(*CreateTaskRequest)(nil),       // 7: runtime.CreateTaskRequest
	(*CreateTaskResponse)(nil),      // 8: runtime.CreateTaskResponse
	(*GetTaskRequest)(nil),          // 9: runtime.GetTaskRequest
	(*GetTaskResponse)(nil),         // 10: runtime.GetTaskResponse
	(*Step)(nil),                    // 11: runtime.Step
	(*CancelTaskRequest)(nil),       // 12: runtime.CancelTaskRequest
	(*CancelTaskResponse)(nil),      // 13: runtime.CancelTaskResponse
	(*ListTasksRequest)(nil),        // 14: runtime.ListTasksRequest
	(*ListTasksResponse)(nil),       // 15: runtime.ListTasksResponse
	(*TaskEventRequest)(nil),        // 16: runtime.TaskEventRequest
	(*TaskEvent)(nil),               // 17: runtime.TaskEvent
	(*LogMessage)(nil),              // 18: runtime.LogMessage
	(*ApproveTaskRequest)(nil),      // 19: runtime.ApproveTaskRequest
	(*ApproveTaskResponse)(nil),     // 20: runtime.ApproveTaskResponse
	(*RejectTaskRequest)(nil),       // 21: runtime.RejectTaskRequest
	(*RejectTaskResponse)(nil),      // 22: runtime.RejectTaskResponse
	(*GetRuntimeStatusRequest)(nil), // 23: runtime.GetRuntimeStatusRequest
	(*RuntimeStatus)(nil),           // 24: runtime.RuntimeStatus
	(*RuntimeMetrics)(nil),          // 25: runtime.RuntimeMetrics
	(*ShutdownRequest)(nil),         // 26: runtime.ShutdownRequest
	(*ShutdownResponse)(nil),        // 27: runtime.ShutdownResponse
	(*HealthCheckRequest)(nil),      // 28: runtime.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 29: runtime.HealthCheckResponse
	(*GetConfigRequest)(nil),        // 30: runtime.GetConfigRequest
	(*GetConfigResponse)(nil),       // 31: runtime.GetConfigResponse
	(*SetConfigRequest)(nil),        // 32: runtime.SetConfigRequest
	(*SetConfigResponse)(nil),       // 33: runtime.SetConfigResponse
	nil,                             // 34: runtime.Task.MetadataEntry
	nil,                             // 35: runtime.CreateTaskRequest.ConfigEntry
	nil,                             // 36: runtime.LogMessage.ContextEntry
	nil,                             // 37: runtime.RuntimeStatus.ConfigEntry
	nil,                             // 38: runtime.GetConfigResponse.ConfigEntry
	(*timestamppb.Timestamp)(nil),   // 39: google.protobuf.Timestamp
}
var file_runtime_proto_depIdxs = []int32{
	0,  // 0: runtime.Task.status:type_name -> runtime.TaskStatus
	1,  // 1: runtime.Task.type:type_name -> runtime.TaskType
	39, // 2: runtime.Task.created_at:type_name -> google.protobuf.Timestamp
	39, // 3: runtime.Task.updated_at:type_name -> google.protobuf.Timestamp
	39, // 4: runtime.Task.started_at:type_name -> google.protobuf.Timestamp
	39, // 5: runtime.Task.completed_at:type_name -> google.protobuf.Timestamp
	34, // 6: runtime.Task.metadata:type_name -> runtime.Task.MetadataEntry
	1,  // 7: runtime.CreateTaskRequest.type:type_name -> runtime.TaskType
	35, // 8: runtime.CreateTaskRequest.config:type_name -> runtime.CreateTaskRequest.ConfigEntry
	6,  // 9: runtime.CreateTaskResponse.task:type_name -> runtime.Task
	6,  // 10: runtime.GetTaskResponse.task:type_name -> runtime.Task
	11, // 11: runtime.GetTaskResponse.steps:type_name -> runtime.Step
	2,  // 12: runtime.Step.status:type_name -> runtime.StepStatus
	39, // 13: runtime.Step.started_at:type_name -> google.protobuf.Timestamp
	39, // 14: runtime.Step.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 15: runtime.ListTasksRequest.filter_status:type_name -> runtime.TaskStatus
	6,  // 16: runtime.ListTasksResponse.tasks:type_name -> runtime.Task
	3,  // 17: runtime.TaskEvent.event_type:type_name -> runtime.TaskEventType
	39, // 18: runtime.TaskEvent.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 19: runtime.TaskEvent.task:type_name -> runtime.Task
	11, // 20: runtime.TaskEvent.step:type_name -> runtime.Step
	18, // 21: runtime.TaskEvent.log:type_name -> runtime.LogMessage
	39, // 22: runtime.LogMessage.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 23: runtime.LogMessage.level:type_name -> runtime.LogLevel
	36, // 24: runtime.LogMessage.context:type_name -> runtime.LogMessage.ContextEntry
	6,  // 25: runtime.ApproveTaskResponse.task:type_name -> runtime.Task
	6,  // 26: runtime.RejectTaskResponse.task:type_name -> runtime.Task
	5,  // 27: runtime.RuntimeStatus.state:type_name -> runtime.RuntimeState
	25, // 28: runtime.RuntimeStatus.metrics:type_name -> runtime.RuntimeMetrics
	39, // 29: runtime.RuntimeStatus.uptime:type_name -> google.protobuf.Timestamp
	37, // 30: runtime.RuntimeStatus.config:type_name -> runtime.RuntimeStatus.ConfigEntry
	39, // 31: runtime.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	38, // 32: runtime.GetConfigResponse.config:type_name -> runtime.GetConfigResponse.ConfigEntry
	7,  // 33: runtime.RuntimeService.CreateTask:input_type -> runtime.CreateTaskRequest
	9,  // 34: runtime.RuntimeService.GetTask:input_type -> runtime.GetTaskRequest
	12, // 35: runtime.RuntimeService.CancelTask:input_type -> runtime.CancelTaskRequest
	14, // 36: runtime.RuntimeService.ListTasks:input_type -> runtime.ListTasksRequest
	16, // 37: runtime.RuntimeService.StreamTaskEvents:input_type -> runtime.TaskEventRequest
	19, // 38: runtime.RuntimeService.ApproveTask:input_type -> runtime.ApproveTaskRequest
	21, // 39: runtime.RuntimeService.RejectTask:input_type -> runtime.RejectTaskRequest
	23, // 40: runtime.RuntimeService.GetRuntimeStatus:input_type -> runtime.GetRuntimeStatusRequest
	26, // 41: runtime.RuntimeService.Shutdown:input_type -> runtime.ShutdownRequest
	28, // 42: runtime.RuntimeService.HealthCheck:input_type -> runtime.HealthCheckRequest
	30, // 43: runtime.RuntimeService.GetConfig:input_type -> runtime.GetConfigRequest
	32, // 44: runtime.RuntimeService.SetConfig:input_type -> runtime.SetConfigRequest
	8,  // 45: runtime.RuntimeService.CreateTask:output_type -> runtime.CreateTaskResponse
	10, // 46: runtime.RuntimeService.GetTask:output_type -> runtime.GetTaskResponse
	13, // 47: runtime.RuntimeService.CancelTask:output_type -> runtime.CancelTaskResponse
	15, // 48: runtime.RuntimeService.ListTasks:output_type -> runtime.ListTasksResponse
	17, // 49: runtime.RuntimeService.StreamTaskEvents:output_type -> runtime.TaskEvent
	20, // 50: runtime.RuntimeService.ApproveTask:output_type -> runtime.ApproveTaskResponse
	22, // 51: runtime.RuntimeService.RejectTask:output_type -> runtime.RejectTaskResponse
	24, // 52: runtime.RuntimeService.GetRuntimeStatus:output_type -> runtime.RuntimeStatus
	27, // 53: runtime.RuntimeService.Shutdown:output_type -> runtime.ShutdownResponse
	29, // 54: runtime.RuntimeService.HealthCheck:output_type -> runtime.HealthCheckResponse
	31, // 55: runtime.RuntimeService.GetConfig:output_type -> runtime.GetConfigResponse
	33, // 56: runtime.RuntimeService.SetConfig:output_type -> runtime.SetConfigResponse
	45, // [45:57] is the sub-list for method output_type
	33, // [33:45] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_runtime_proto_init() }
func file_runtime_proto_init() {
	if File_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_proto_goTypes,
		DependencyIndexes: file_runtime_proto_depIdxs,
		EnumInfos:         file_runtime_proto_enumTypes,
		MessageInfos:      file_runtime_proto_msgTypes,
	}.Build()
	File_runtime_proto = out.File
	file_runtime_proto_goTypes = nil
	file_runtime_proto_depIdxs = nil
}
